### ISSUE TITLE
[PW-4740] Get Internal Error for Klarna Order v.6.7.0

### ISSUE THREAD

**Issue by crossgate9** [Adyen/adyen-magento2#1037]
We are using the 6.7.0 module on Magento Cloud Enterprise Version. 
The installation is over Composer. 

We got the report that the Klarna payment cannot be processed when there is a discount in the quote. 
All the rest of HPP method, PayPal, Credit card works fine. 

On the frontend, the customer could get the error message:
"Error with payment method. please select different payment method. "

And we can find the following message in the log file:
AdyenLoggerTest.INFO: JSON Response to Adyen:{"status":500,"errorCode":"903","message":"Internal error: Result from Open Invoice service does not contain a redirect URL","errorType":"internal"} {"is_exception":false} []

The entry before this error message is the response, and we can find the "returnUrl" in JSON. 
Please advise. 

Thanks in advance.

**Comment by acampos1916** [comment]
Hello @crossgate9, sorry for the late reply. We're currently investigating this issue and will let you know of any progress made

**Comment by paulstolkbbd** [comment]
I get the same kind of error:
[2021-06-09 08:43:42] AdyenLoggerTest.ERROR: 903: Internal error: Result from Open Invoice service does not contain a redirect URL {"is_exception":false} []
[2021-06-09 08:43:42] AdyenLoggerTest.ERROR: Internal error: Result from Open Invoice service does not contain a redirect URL {"is_exception":false} []

Like OP mentioned: only with Klarna and when using a coupon code for discount. 
Any progress on this issue yet? Since this payment method does not work now, when using a discount.

**Comment by acampos1916** [comment]
@paulstolkbbd thanks for the report. It is currently being worked on and a fix will be out ASAP.

**Comment by charlottegeven** [comment]
Is there already more information about this issue?

Hope to hear it, thanks.

**Comment by acampos1916** [comment]
Hello @charlottegeven @paulstolkbbd @crossgate9 it has been fixed in #1074 and will be released this week.

Cheers!

**Comment by acampos1916** [comment]
6.7.2 has been released including #1074
