### ISSUE TITLE
SQL error resulting in block of cron

### ISSUE THREAD

**Issue by TommyKolkman** [Adyen/adyen-magento2#107]
System:
Magento 2.1.5
Adyen 2.0.3

This seems to occur more often now, tried to take this up with Adyen before, but to no avail, so let's see if this can be fixed.

Every now and then an order comes in without a shipping address. Which is weird, because nothing seems to fail in the checkout.

![adyen](https://cloud.githubusercontent.com/assets/837198/25576312/2904c47a-2e5e-11e7-8d49-e21a9048bc94.png)

So, this order comes in, and from then on, the Adyen cron fails and therefore blocks execution for new incoming orders as well:

```SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4834934890077816' for key 'ADYEN_ORDER_PAYMENT_PSPREFERENCE', query was: INSERT INTO `adyen_order_payment` (`pspreference`, `merchant_reference`, `payment_id`, `payment_method`, `amount`, `total_refunded`, `created_at`, `updated_at`) VALUES (?, ?, ?, ?, ?, ?, '2017-05-01 08:50:06', '2017-05-01 08:50:06')```

When I remove the order with that PSP reference (which has the corresponding order number) from `adyen_order_payment`, everything functions like it should, but the order I removed is of course not going to be processed anymore. I've got to tell my client to fix that with the customer themselves, which is really not what we want.

**Comment by paales** [comment]
The order flow is as follows:
Create order > Make request for PSP > Create invoice. If an order is missing the shipping information it is because Magento is doing something wrong (or Adyen is causing an exception, but then you should be able to see it).

I believe there were some address issues in some versions of Magento 2.1. Maybe it is this bug? https://github.com/magento/magento2/issues/6869

Of course the Adyen module shouldn't become stuck when a single order throws an exception.

**Comment by rikterbeek** [comment]
HI @TommyKolkman,

This Integrity constraint violation is becasue this code is execute twice and that should never happen. Where does it fail the first time ? Because the error that you are referring to is caused becasue this code has already run and somehow after this code crashes. What we can do is add this in a try catch so it will continue but there is an issue somewhere else causing this notification not to process correctly. 

Regards,
Rik
Adyen

**Comment by AdilShoukatConstant** [comment]
Hi @rikterbeek ,

I am also facing same issue. Any help.

**Comment by yasirrose** [comment]
Hi, 

I am facing the same issue. Any help to fix it?

thanks

**Comment by rikterbeek** [comment]
Hi @yasirrose,

Did you figured out why it was failing the first time ?

Regards,
Rik
Adyen
