### ISSUE TITLE
404 not found - notification URL

### ISSUE THREAD

**Issue by yasirrose** [Adyen/adyen-magento2#110]
Hi, 

I hope you all are doing well. 

I have magento 2 site and i have implemented adyen-magento2 paymets. I am facing issue related to adyen notification url: 

I am using following url: SiteURL/adyen/process/json

When i test configuration. I am getting following results 
HTTP test - Merchant Account:

Test 1: test_AUTHORISATION_1
    ResponseTime_ms: 315
    ResponseCode: 404
    Output: 
Error 404: Not Found
  Test 2: test_AUTHORISATION_2
    ResponseTime_ms: 315
    ResponseCode: 404
    Output: 
Error 404: Not Found
  Test 3: test_AUTHORISATION_3
    ResponseTime_ms: 315
    ResponseCode: 404
    Output: 
Error 404: Not Found
  Test 4: test_AUTHORISATION_4
    ResponseTime_ms: 315
    ResponseCode: 404
    Output: 
Error 404: Not Found

Can any body know what could be the issue?

**Comment by yasirrose** [comment]
I noticed that my url is givng 401 unauthorized code if i access it through postman or directly hitting in the browser

**Comment by rikterbeek** [comment]
Hi @yasirrose,

That you get a 401 is correct it is using HTTP authentication so you need to add this into the header.
Make sure your endpoint is ending with /adyen/process/json and method is set to JSON. As well make sure your server is accepting server communication to this url and you don't have our service listed as bot because then it will not go through to the controller of Magento. Please contact your hosting provider as well most of the times these issues are related to server configuration.

Regards,
Rik
Adyen
