### ISSUE TITLE
Unable to process binding "afterRender: function (){return renderCheckoutComponent() }"

### ISSUE THREAD

**Issue by killoff** [Adyen/adyen-magento2#1102]
**Describe the bug**
TypeError: Unable to process binding "afterRender: function (){return renderCheckoutComponent() }"
Message: undefined is not an object (evaluating 'quote.shippingAddress().
                                        street.
                                        ...
  at renderCheckoutComponent(/static/version1626083548/frontend/Drinks/custom/fr_CH/Adyen_Payment/js/view/payment/method-renderer/adyen-hpp-method.js:263:47)

**To Reproduce**
1. Go to Magento Checkout
2. Go to Payment Methods

**Expected behavior**
No exception

**Magento version**
2.4.1

**Plugin version**
7.0.1

**Screenshots**

![Screenshot 2021-07-14 at 12 18 35](https://user-images.githubusercontent.com/3583507/125605985-a3ed876d-2275-4409-ad08-e8c16254f613.png)

**Smartphone (please complete the following information):**

Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/34.2  Mobile/15E148 Safari/605.1.15

--

**Additional context**
We have this error several times per day catched by sentry, meaning it reproduces approx. in 1% of checkout sessions.

**Comment by cyattilakiss** [comment]
Hi @killoff ,

Thank you for raising this issue. On develop branch this issue has already been fixed in the pull request: https://github.com/Adyen/adyen-magento2/pull/1095/files#diff-7de10d96985d87af113c028849c660af1c3365ec9a89f8a63af784635d16bea2R267

We are going to release the new patch version soon, please after release let me know if it solved this issue for you as well.

Best,
Attila
Adyen
