### ISSUE TITLE
[PW-5167] GiveX gift card integration doesn't work

### ISSUE THREAD

**Issue by m-molla** [Adyen/adyen-magento2#1106]
**Describe the bug**
GiveX gift card integration doesn't work,
there is no gift card fields are rendered.

**To Reproduce**
1. Enabled GiveX gift card by adyen or givex provider
2. try to checkout with Givex payment method

**Expected behavior**
Gift Card input fields will be render.

**Magento version**
2.4.2

**Plugin version**
7.1.0

**Screenshots**
Checkout page payment section screenshot
[https://prnt.sc/1btpinj](https://prnt.sc/1btpinj)

**Additional context**
```
js error on checkout page
Error: The passed payment method is not a valid Checkout Component
    at t.e.handleCreateError (bundle.js:23)
    at t.e.handleCreate (bundle.js:23)
    at t.e.create (bundle.js:23)
    at t.a.create (bundle.js:23)
    at Object.renderCheckoutComponent (adyen-hpp-method.js:344)
    at afterRender (eval at createBindingsStringEvaluator (knockout.js:2982), <anonymous>:3:174)
    at init (after-render.js:17)
    at knockout.js:3358
    at Object.ignore (knockout.js:1470)
    at knockout.js:3357
```

**Comment by peterojo** [comment]
Hi @m-molla!
Thanks for reporting this issue, we will investigate it and work on a fix in the coming weeks.

**Comment by peterojo** [comment]
Hi @m-molla gift card integrations in this plugin currently use a hosted payment platform (HPP) for processing the payments instead of rendering the component in checkout. We are working to fix the error message but in order to use the givex gift card please set the property `shouldFallbackToHPPForGiftCard=true` in you Adyen Customer Area (Settings > Account Properties)
