### ISSUE TITLE
Please check your model annotations

### ISSUE THREAD

**Issue by marcoboom** [Adyen/adyen-magento2#1172]
I want to use Adyen\Payment\Api\Data\OrderPaymentInterface as an extension attribute on another object. 

With the Magento Rest API the data is not correctly send to the frontend due to wrong annotations in the model interface

For example: https://github.com/Adyen/adyen-magento2/blob/7.2.0/Api/Data/OrderPaymentInterface.php#L139

The getter annotates that is wil return a int or null but the setter has a string as parameter. In the Rest API the result of payment_method now is 0 instead of "mc" or "ideal".

**Comment by Morerice** [comment]
Hi @marcoboom,

Apologies for the delay. The specific annotation mentioned in this issue will be fixed in the linked PR. We have also created an internal ticket to go over all the interfaces under the `Api\Data` directory (and their implementations) and add typing to all the functions contained in these interfaces.

Regards,
Jean
Adyen
