### ISSUE TITLE
Cron error while processing the notifications

### ISSUE THREAD

**Issue by adjogic** [Adyen/adyen-magento2#1226]
When cron is processing received notifications it throws an error and the order gets stuck in Pending Review status.
`Class Adyen\Payment\Model\ResourceModel\Invoice\Invoice\Collection does not exist {"is_exception":false} []`
The same thing happens in admin when trying to manually change the status to processing

**To Reproduce**
1. Place an order
2. Wait for webhook callback
3. Check cron logs

**Magento version**
2.4.3

**Plugin version**
7.3.1

**Comment by tnaber** [comment]
Hi @adjogic,

Thank you for opening this issue. I did not manage to recreate this bug on my local setup. I see that the path tries to enter ```Invoice``` twice, this path does not exist indeed. Could this be caused by your local changes?

To further investigate, could you provide me with the following info:

- The full logs regarding this issue
- Does still happen for all callback types?
- Does the issue also occur when only having the module-payment installed?

 Furthermore, a more detailed description of the steps to reproduce might be helpful. However, if this issue occurs for every callback I can imagine that it does not have to be more specific.

Cheers,
Titus

**Comment by adjogic** [comment]
Hi @tnaber 

We did a bit more digging and it looks like the issue was thrown in a custom module when getting a collection
`
$adyeninvoice = $this->adyenInvoiceFactory->create()->getCollection()
                    ->addFieldToFilter('pspreference', $pspreference)
                    ->getFirstItem();
`
