### ISSUE TITLE
[PW-6309] Make Magento_Paypal not required

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#1326]
**Describe the bug**
The module "Magento_Paypal" are required to have enabled in Magento 2 before Adyen module will be able to work.
If you dont use paypal it should be possbile to disable the paypal module. Adyen module must see if the module is active, and if not not show the paypal payment. 

**To Reproduce**
SSH bin/magento module:disable Magento_Paypal -> 
Unable to change status of modules because of the following constraints:
Cannot disable Magento_Paypal because modules depend on it:
Adyen_Payment: Adyen_Payment->Magento_Paypal

**Magento version**
2.4.3

**Plugin version**
8.1.0

**Comment by Morerice** [comment]
Hi @dronerdk,

Thanks for opening this issue. Currently our module depends on the default Magento PayPal module since one of its tables (`paypal_billing_agreement`) is being used by the Adyen module. We will be conducting an investigation in the near future to identify if this functionality can be changed to utilize a new table created by the Adyen module, which would eliminate this dependency.

Thanks,
Jean
Adyen

**Comment by candemiralp** [comment]
Hello @dronerdk,

Finally, our plugin was decoupled from `Magento_Paypal` module on V9.

Best Regards,
Can
