### ISSUE TITLE
[PW-6306] Open invoice data incorrect with non- base currency: line amountExcludingTax is in base currency while amountIncludingTax is in FC

### ISSUE THREAD

**Issue by ThijsdejongSNC** [Adyen/adyen-magento2#1356]
**Describe the bug**
In case of a foreign currency, the amountExcludingTax + taxAmount does not equal the amountIncludingTax causing klarna error "Acquirer Error (BAD_VALUE : order_lines[0].total_tax_amount)". 

**To Reproduce**
1. Create a M2 store with EUR as base currency and SEK as optional currency. Enable klarna as option for SEK / Sweden
2. Select SEK as the current currency in the front end
3. Add a random configurable product to card
4. Go to checkout and enter a Swedish address (so klarna with SEK is an option).
5. Checkout  and assert "Acquirer Error (BAD_VALUE : order_lines[0].total_tax_amount)" error or debug getOpenInvoiceData in CheckoutDataBuilder and watch the data in $formFields['lineItems'].

**Expected behavior**
In the line item data, the amountExcludingTax should be equal to amountIncludingTax minus taxAmount.

**Magento version**
2.4.3-p1

**Plugin version**
7.3.5

**Screenshots**

![image](https://user-images.githubusercontent.com/12978537/153707500-5418262c-b7c0-4682-a80e-ef256f81ae37.png)

![image](https://user-images.githubusercontent.com/12978537/153707205-ede0066a-a28f-4ef7-8f82-9ff765a33cd9.png)

**Additional context**
* tax rate for this shipping combination is set to 26%
* Additional small remark: the shipping line item calculates the vat rate back and, trough rounding, can calulate a slightly different rate with lots of decimals
![image](https://user-images.githubusercontent.com/12978537/153707408-fef19c0a-03ea-4b77-9645-5a595055c2d6.png)

**Comment by ThijsdejongSNC** [comment]
I've looked into this a little deeper, In Adyen\Payment\HelperChargedCurrency:
`
        return new AdyenAmountCurrency(
            $item->getPrice(),
            $item->getQuote()->getQuoteCurrencyCode(),
            $item->getDiscountAmount(),
            $item->getPriceInclTax() - $item->getPrice(),
            null,
            $item->getPriceInclTax()
        );`

$item->getPrice() Always returns the price in base currency.

**Comment by tnaber** [comment]
Hi @ThijsdejongSNC,

Thank you for opening this issue and solo adding your own research. You state that the expected behaviour is the ```amountExcludingTax = amountIncludingTax - taxAmount```, looking at your screenshot it seems that this condition is met. However, there is definitely some bug going on as the tax amount does not match the BTW in the second screenshot.   Regarding your own research, ```$item->getPrice()``` should return the non-base price, if this is not the case it will most likely cause this problem but I don't see any direct indications of that behaviour in the code. I will add this to our backlog for further investigation.
If you would like to contribute with your own solution that would also be greatly appreciated, feel free to open a PR! :)

Finally, we would like to ask you whether you are using Magento Vertex for your tax calculations?

Cheers,
Titus

**Comment by ThijsdejongSNC** [comment]
hi @tnaber,

We're not using Magento Vertex. It seems like a bug in Magento that item->getPrice() is returning the price in BC. 

I'll have a look at this later, but a PR would be a fix avoiding the magento bug and calculating price another way. 

Cheers,
Thijs
