### ISSUE TITLE
Some creditcard payments are not able to proceed the checkout

### ISSUE THREAD

**Issue by nwiegers01** [Adyen/adyen-magento2#1396]
If I choose to pay by credit-card, some credit-cards are supported and others are not. The credit-card provider is the same and both credit cards are Mastercard. 

For example as I want to pay by Mastercard, number _**2222 4107 4036 0010**_ is not supported and **_5555 3412 4444 1115_** is supported, although they are both Mastercard and all the credentials are filled in correctly.
The credit-cards numbers are from the Adyen Test Card Number page and both are issuing the correct country for our case.

Adyen Test Card Numbers page:
https://docs.adyen.com/development-resources/test-cards/test-card-numbers#mastercard

1. Add a product to your cart and go thru the checkout process.
2. Choose for Credit-Card payment in the checkout.
3. Enter _**2222 4107 4036 0010**_ as the card number.
4. Enter **_03/30_** as the expire date.
5. Enter _**737**_ as validation code.
6. Enter a random name.

**Expected behavior**
The credit-card payment is accepted and you can proceed thru the checkout.

**Actual behavior**
The payment returns an error that it is not accepted/supported.

**Magento version**
2.4.3-P1

**Plugin version**
8.1.1

**Screenshots**
![AdyenCreditIssue](https://user-images.githubusercontent.com/92866914/158583506-e6acbcc2-fe29-4724-a1e3-3b3b5e991af2.png)
![AdyenCreditIssue2](https://user-images.githubusercontent.com/92866914/158584153-68e5ed9b-1bb1-4f27-bca6-c0bb6ab30d98.png)

**Desktop:**
 - OS: Ubuntu 20.04.4 LTS
 - Browser Chrome
 - Version 99.0.4844.51

**Smartphone:**
 - Device: iPhone 12
 - OS: IOS 15.3.1
 - Browser: Safari

**Comment by Morerice** [comment]
Hi @nwiegers01,

Thanks for opening this issue. Our plugin utilizes the Adyen checkout component for the customer's checkout experience. The component expects a list of [brands](https://docs.adyen.com/payment-methods/cards/web-component#optional-configuration) that should be passed to it, when initialized [here](https://github.com/Adyen/adyen-magento2/blob/3cbc8ad6e7069b04ec63ea64d0810fc3588c0de9/view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js#L127). Could you please check which brands you are passing to the component? In a normal instantiation of our magento plugin, the brands will be obtained from the [Credit Card Types](https://docs.adyen.com/plugins/magento-2/set-up-the-payment-methods-in-magento#api-credit-card-payments) field.

Also, since I think you already have an open ticket with our support team and this issue does not seem to be specific to the plugin, I will close the ticket and we can continue our communication trough the support ticket. If it turns out that something within the plugin is contributing to this issue, we can re-open this issue to make both the issue and the solution public.

Best regards,
Jean
Adyen
