### ISSUE TITLE
Again: Orders staying in Payment Review after OFFER_CLOSED

### ISSUE THREAD

**Issue by killoff** [Adyen/adyen-magento2#1408]
**Description**

I would like to reference this issue again:
https://github.com/Adyen/adyen-magento2/issues/1193

We are on the latest 8x version, i.e. 8.1.1 of plugin and noticed same behaviour here:

Orders that were paid with saved credit cards remain in status **Payment Review** even though `OFFER_CLOSED` notification sent from Adyen.

It seems, that `Cron.php` no longer takes account of saved payment methods (`adyen_oneclick`):
```
                /*
                 * Return if payment method is cc like VI, MI
                 */
                $isCCPaymentMethod = $this->_order->getPayment()->getMethod() === 'adyen_cc';

                /*
                * If the order was made with an Alternative payment method,
                *  continue with the cancellation only if the payment method of
                * the notification matches the payment method of the order.
                */
                if ( !$isWalletPaymentMethod && !$isCCPaymentMethod && strcmp($notificationPaymentMethod, $orderPaymentMethod) !== 0) {
                    $this->_adyenLogger->addAdyenNotificationCronjob(
                        "The notification does not match the payment method of the order,
                    skipping OFFER_CLOSED"
                    );
                    break;
                }

```

Before it was a fix proposed (in the PW-5668 I mentioned above):

```
              $isOrderCc = strcmp(
                        $this->_paymentMethodCode(),
                        'adyen_cc'
                    ) == 0 || strcmp($this->_paymentMethodCode(), 'adyen_oneclick') == 0;
```

But at the moment I can't find the check against `strcmp($this->_paymentMethodCode(), 'adyen_oneclick')` in any of 
plugin versions 7x or 8x.

Was it made intentionally or the fix was lost between merge requests?

**To Reproduce**
1. Place an order with saved credit card
2. Make sure order gets Payment Review status
3. Ensure that notification OFFER_CLOSED sent from Adyen
4. Confirm that order remains in Payment Review status

**Expected behavior**
Order should be cancelled

**Magento version**
2.4.2

**Plugin version**
8.1.1

**Screenshots**
![Screenshot 2022-03-21 at 16 08 47](https://user-images.githubusercontent.com/3583507/159290800-c5c8d29f-ce37-4d63-9786-8bd8a2d040b9.png)

**Comment by tnaber** [comment]
Hi @killoff,

Thank you for opening this issue. After looking at #1193, I see that the fix was never properly implemented for the oneclick scenario. We will be opening a PR to update this shortly.
 
Cheers,
Titus

**Comment by pknap** [comment]
Hi @tnaber, not sure if I should open a third ticket for this, but I think that this error still occurs for some HPP payment methods, for example Klarna:

![image](https://user-images.githubusercontent.com/1770746/217533299-d48b99da-2529-4f81-9724-fb528bf2cd4f.png)

``
[2023-01-22 12:47:06] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Processing notification 7883210 {"is_exception":false} []
``

``
[2023-01-22 12:47:06] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: {"entity_id":"7883210","pspreference":"N575VXTLZSGLNK82","merchant_reference":"1000718790","event_code":"OFFER_CLOSED","success":"true","payment_method":"klarna_account","amount_value":"7596","amount_currency":"EUR","live":"false","done":"0","processing":true,"error_count":"0","created_at":"2023-01-22 12:36:29"} {"is_exception":false} []
``

``[2023-01-22 12:47:06] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Created comment history for this notification {"is_exception":false} []
``

``
[2023-01-22 12:47:06] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Updating the Adyen attributes of the order {"is_exception":false} []
``

``
[2023-01-22 12:47:06] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Processing the notification {"is_exception":false} []
``

``
[2023-01-22 12:47:06] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: The notification does not match the payment method of the order,
                    skipping OFFER_CLOSED {"is_exception":false} []
``

``
[2023-01-22 12:47:07] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Notification 7883210 is processed {"is_exception":false} []``

So this condition: 

https://github.com/Adyen/adyen-magento2/blob/7.3.13/Model/Cron.php#L1232

is not met, because klarna is not wallet, nor credit card, and 

`strcmp($notificationPaymentMethod, $orderPaymentMethod) !== 0`

is also not true, because `$notificationPaymentMethod` is `klarna_account` but `$orderPaymentMethod` is `klarna`. Could you suggest what would be the proper way to fix it?

**Comment by bartoszkubicki** [comment]
Still an issue

**Comment by lano-vargas** [comment]
@bartoszkubicki  What version are you encountering this issue please ?
