### ISSUE TITLE
[PW-6518] Webhook Helper does not use Store ID to select Order

### ISSUE THREAD

**Issue by pmzandbergen** [Adyen/adyen-magento2#1432]
https://github.com/Adyen/adyen-magento2/blob/49b5eaca8bdfa9bf03bf77e1d3f88542c21d8596/Helper/Webhook.php#L1890-L1892

The order is selected by the Increment ID only, without using a Store ID. While this will work OK in most cases, you should filter by Store ID as well since the Order Increment ID is **not necessarily** unique in a multi-store environment. Example:

```
        $searchCriteria = $this->searchCriteriaBuilder
            ->addFilter('increment_id', $incrementId)
            ->addFilter('store_id', $storeId)
            ->create();
```

_Note: You might need to update your Notification model to keep track of the Store ID._

**Comment by Morerice** [comment]
Hi @pmzandbergen,

Apologies for the delay. Although it's true that the increment ID is not necessarily unique, Magento by default utilizes [this pattern](https://github.com/magento/magento2/blob/1df4565907d40f14ee1c753cc2de2ce567bfa8d7/app/code/Magento/SalesSequence/Model/Sequence.php#L22) to generate the increment ID, which uses `$this->meta->getActiveProfile()->getPrefix()` to differentiate between different stores.

Hence, if this default functionality is correctly overridden, it should be the admin's responsibility to ensure that the generated increment ID differentiates orders between different stores.

From our end it is not possible to specify the store ID as a separate field in the webhook, since ultimately this is functionality that is used by all Adyen merchants, not just Magento 2 users.

Regards,
Jean
Adyen
