### ISSUE TITLE
Magento 2.4.4 Rest API: Workaround for integration token

### ISSUE THREAD

**Issue by marcoboom** [Adyen/adyen-magento2#1457]
Since version 8 an integration token is needed to access the "anonymous" Adyen Rest API endpoints of Magento.

Now in the new Magento 2.4.4 release the following happened:

_Integration tokens can no longer be used for API Bearer token authentication. Previously, an integration token could be used as a standalone key for token-based authentication. However, this behavior has been disabled by default due to the security implications of a never-expiring access token. The previous behavior can be enabled through the command line or Admin. See [Token-based authentication](https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-token.html)._

Enabling the previous behavior is future wise not an option.

What will be your workaround for all Rest API endpoints where the ACL <resource ref="Adyen_Payment::guestPaymentMethods"/> is active?

**Comment by Morerice** [comment]
Hi @marcoboom

Apologies for the late reply. There will be no workaround required, since the REST API endpoints that were previously accessed using API Bearer token authentication, can also be accessed using OAuth-based authentication, that Magento is now recommending (using the consumer key, consumer secret, access token, and access token secret). 

Therefore what would be required from your end would be to utilize this authentication method instead of the older never-expiring access token. From our end we have tested this functionality using [this](https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-token.html#standalone-oauthphp) code sample provided by Magento.

I will close this issue, but feel free to re-open it if there is something that is not clear, or if there are further questions.

Regards,
Jean
Adyen
