### ISSUE TITLE
Webhook is not working and throwing error in cron job adyen_payment_process_notification

### ISSUE THREAD

**Issue by vipinroy** [Adyen/adyen-magento2#1681]
**Describe the bug**
We can see an error as below in adyen 8.3.5 version at the time of running cron job: adyen_payment_process_notification.

report.CRITICAL: Error when running a cron job {"exception":"[object] (RuntimeException(code: 0): Error when running a cron job at vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:367, TypeError(code: 0): Argument 2 passed to Adyen\\Payment\\Helper\\PaymentMethods::isAutoCapture() must be of the type string, null given, called in vendor/adyen/module-payment/Helper/Webhook/AuthorisationWebhookHandler.php on line 108 at vendor/adyen/module-payment/Helper/PaymentMethods.php:576)"} []

**To Reproduce**
1. Create an order using adyen test credit card
2. Check the cronjob adyen_payment_process_notification, we can see the cron is failing
3. Check var/log/exception.log

**Expected behavior**
The cronjob will run correctly

**Magento version**
2.4.2-p2

**Plugin version**
8.3.5

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by Morerice** [comment]
Hi @vipinroy,

Thanks for opening this issue. The issue seems to be occurring because the second parameter of [this](https://github.com/Adyen/adyen-magento2/blob/f576ecff18dfdb5e123ccfa6cb3c65a609068bd4/Helper/Webhook/AuthorisationWebhookHandler.php#L108) function is resulting in null.

`$notification->getPaymentMethod()` should always return the payment method name as a string. Could you please check the `adyen_notification` table and check the value of the `payment_method` column, on the notifications where this issue is occurring?

Thanks,
Jean
Adyen

**Comment by Morerice** [comment]
Hi @vipinroy,

Did you have time to check what I mentioned in my previous comment?

Thanks,
Jean
Adyen

**Comment by Morerice** [comment]
Closing the issue due to inactivity and also since we weren't able to reproduce it. Feel free to re-open it if the investigation mentioned in my previous comment yields some results.

Thanks,
Jean
Adyen
