### ISSUE TITLE
Notification webhook for headless integration

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-magento2#1710]
**Describe the bug**
If you run an headless e-commerce, your frontend URL doesn't point to Magento anymore.
It means Adyen module notification URL is not accessible anymore even if you set a custom URL for Magento backoffice.

I'm maybe missing something? 

**To Reproduce**

Requirements: your Adyen notification URL is your Magento custom backoffice URL + /adyen/process/json

1. Place an order on your website (headless)
2. Wait for Adyen notification
3. You will never receive it as Magento backoffice redirects your backoffice URL to the default config one 

**Expected behavior**

Adyen notifications should be processed on Adobe Commerce even if you use an headless website.

Custom Magento 2 backoffice URL is accessible for REST API endpoints. For headless we could use REST endpoint.

**Magento version**
2.4.5

**Plugin version**
8.3.5

**Comment by Morerice** [comment]
Hi @jonathanribas,

Thanks for opening this issue. Few possible solutions:

* Is it not possible to configure the webhook on Adyen side to be sent to frontend URL + `/adyen/process/json` and then forward that to your backend url? Since your frontend will be able to communicate with the backend.

* Could you expose the Magento backoffice URL + `adyen/process/json` so that you're not redirected when you receive the notification?

If you have any other ideas how to tackle this issue we'd be happy to hear them.

Thanks,
Jean
Adyen

**Comment by Morerice** [comment]
Hi @jonathanribas,

Would it be possible to check your magento logs or even your nginx logs to check why the redirection is occurring? We have quite a large number of headless merchants, so I would assume that this problem would have come up earlier if it was across the board.

Regards,
Jean
Adyen

**Comment by jonathanribas** [comment]
Hi @Morerice, 
Our M2 project was misconfigured, that's why we weren't able to access our backoffice on a custom URL.
Sorry!
