### ISSUE TITLE
Adyen v8.3.5 is backward incopatible for refunds of orders paid with module v6.6.9

### ISSUE THREAD

**Issue by kanevbg** [Adyen/adyen-magento2#1769]
The problem is in the action of refund. When you have paid and completed orders with module v6.6.9 and then you upgrade the module to v8.3.5 and do refund of the orders completed with the older module from the magento admin backend, by creating the credit memo for the paid invoice (online refund), the orders will get stuck in invalid state and status. The state is pending_payment and the status is complete. I can not find the reason for this to happen. Not only it's invalid state/status but it's invalid order flow to go from complete state to pending_payment state. This causes serious order-management issues in production.

**Expected behavior**
The refunded order should remain in state complete if it's partial refund or switch to closed state if it's full refund without ever getting back to the pending_payment state.

**Magento version**
2.3.7-p2

**Plugin version**
8.3.5

If I do the same process with orders paid and completed with module v8.3.5 no problem occurs, only with orders paid with the module before upgrade. We have upgraded from 6.6.9 to 8.3.5.

EDIT: These are the current order processing configs:
![image](https://user-images.githubusercontent.com/11477130/196242719-0112be92-3298-40ed-954c-d64e8dfb4461.png)

It is happening for sure with methods adyen_cc and adyen_hpp. If you need more info please let me know.

**Comment by jerome-breton** [comment]
I have the same problem upon upgrading from 7.1.0 to 7.3.12.

My analysis so far led me to these two upgrades :
- [[PW-5364]](https://github.com/Adyen/adyen-magento2/pull/1141) introduces new column capture_status on Adyen Payment and no default value is set for older payments
- [[PW-6987]](https://github.com/Adyen/adyen-magento2/pull/1652) introduces a feature that forces the state to pending_payment on invoice after_save event if order has not been fully payed

But this [AdyenOrderPayment::isFullAmountFinalized()](https://github.com/Adyen/adyen-magento2/blob/dc854e3a68f6ee99f16be1c6a2fa93fd70843719/Helper/AdyenOrderPayment.php#L161) fails to validate in my case, because older Adyen Payments are filtered because they do not have "Auto Capture" status. For now, I feel that the analysis is enough for me, has I am using Auto Capture, so I will try to force status on older payments.

For others, isfullAmountFinalized() seems to have another check if payments one is false, that check invoice totals against order total. But in my case it also fails to validate, but I will not investigate further for now.

**Comment by kanevbg** [comment]
@jerome-breton Well done, **thank you** for joining the issue!

In my case I can confirm that orders experience the issues on refund only if capture_status is null. _No_ single order has received pending_payment on refund if the capture_status for it's payment is set, so same relation is true in my case too.

Suggestion for the Adyen's developers - store the module version for each payment, this will allow executing operations related to upgrade/downgrade incompatibilities and issues in feature. You may not utilize that at all but may be useful for agencies to resolve issues on their side.  But how knows, it may end up useful for setup upgrades or module build-in console commands for exploring specific payments for issue and eventually fixing them.

**Comment by Morerice** [comment]
Hi guys

Apologies for the delay. 

With regards to @kanevbg's issue, unfortunately with a jump between two major versions, there's going to be a number of breaking changes, this being one of them. Our suggestion for these orders would be to refund them trough the Adyen customer area and then create an offline credit memo to reflect that within magento.

For @jerome-breton, based on the information provided the issue seems to definitely be linked to the `capture_status` field. This field is used to identify if the attempted amount to be refunded has already been captured. If you are using an auto capture setup, it should be safe to set this field to `Auto Captured` for all orders, which in turn should enable you to process the refunds.

Regards,
Jean
Adyen

**Comment by Morerice** [comment]
Closing this issue since this is not something we will address with any functionality. Please refer to my previous comment for more information on what can be done in these two scenarios.

Regards,
Jean
Adyen
