### ISSUE TITLE
Notification cron crash if FRAUD-CANCELLED

### ISSUE THREAD

**Issue by Quentin-Sch** [Adyen/adyen-magento2#1793]
Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Describe the bug**

**To Reproduce**
1. Make a transaction (credit card) that notifify Magento 2 with a FRAUD-CANCELLED notification (d'ont know how the user made it, it's in test env)
2. Run the cron adyen_payment_process_notification
3. In the table adyen_notification the processing is set to 1 by the cron
4. Get an error from the cron "Error when running a cron job", no stack, no more information :/. processing stay at 1, error_message column is null

**Expected behavior**
No error from the cron adyen_payment_process_notification

**Magento version**
2.4.3-p1

**Plugin version**
8.8.0

**Additional context**
Fresh install of the plugin, everything else working fine (validated payment, refund...)

**Comment by Morerice** [comment]
Hi @Quentin-Sch,

Since no code snippet is referenced in this issue and also because we prefer to not publicize psp references, could you please open a ticket with our support team by emailing support@adyen.com? We will be in close contact with you and our support team to verify this issue.

Thanks,
Jean
Adyen
