### ISSUE TITLE
iOS 14.1 - 14.5 bug during checkout - adyen/payment-module

### ISSUE THREAD

**Issue by onurayko** [Adyen/adyen-magento2#1801]
**Describe the bug**
Payment issue being reported from iPad users.

adyen/payment-module bug between iOS 14.1 and 14.5 where after completing the shipping step and clicking 'Next' to go the payment step, the checkout process lags out and takes you back to the first step (before the shipping step).

Attempted to update the module from 8.4.0 to 8.8.0 but this did not resolve the issue.

Multiple attempts on 'Next' button sometimes causes browser crash with following error:

> a problem repeatedly occurred on "url-to-site-shipping-step"

**To Reproduce**
1. adyen/payment-module version 8.4.0 or 8.8.0
2. Magento version 2.4.4
3. Use iPhone or iPad with iOS 14.1 to 14.5 and attempt full checkout process.

**Expected behavior**
The expected behaviour is that if all relevant fields are filled, there should be no issue going from shipping step to payment step.

**Magento version**
2.4.4

**Plugin version**
adyen/module-payment 8.4.0 (same issue on 8.8.0)

**Smartphone (please complete the following information):**
 - Device: Any iPhone or iPad that can run iOS 14.1 to 14.5
 - OS: iOS 14.1 - 14.5
 - Browser Safari

**Comment by Morerice** [comment]
Hi @onurayko,

Thanks for opening this issue. However, since no code fragment is referenced and since we are not able to reproduce this issue, please open a ticket with our support team: support@adyen.com where we will request some further details.

If we confirm that the issue is related to the module, we will update this issue with the relevant information.

Regards,
Jean
Adyen
