### ISSUE TITLE
Magento 2.2

### ISSUE THREAD

**Issue by FreekVandeursen** [Adyen/adyen-magento2#182]
Magento 2.2 is expected to be released soon, with version update for the magento framework to 100.2. Since the Adyen module currently depends on the 100.1 version this needs to be updated and tested.

**Comment by rikterbeek** [comment]
Hi @FreekVandeursen,

We are this week looking in the compatibility with magento 2.2 if it works we will update our dependencies so you can install our extension.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @FreekVandeursen,

We don't see any issues with Magento 2.2.
So we have cleanup a bit the dependencies so you can easily upgrade in the future. If we see any problems with new versions we will try to be backwards compatible otherwise we will put restrictions back in the composer file.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
https://github.com/Adyen/adyen-magento2/pull/184
