### ISSUE TITLE
CAPTURE_FAILED notification sent after payment successfully completed

### ISSUE THREAD

**Issue by killoff** [Adyen/adyen-magento2#1833]
**Additional context**
Referencing the issue PW-5812 https://github.com/Adyen/adyen-magento2/issues/1234
which was fixed in version 7.3.2
The difference is, now the capture failed reason specified: NO_RESPONSE_WITHIN_TIMEOUT

**Describe the bug**
After Payment is authorised and order is completed, CAPTURE_FAILED (reason: NO_RESPONSE_WITHIN_TIMEOUT)
notification sent by Adyen, which has no effect - order remains in status Processing.

**To Reproduce**
Place order with TWINT payment method
We face this issue in a small number of orders, so there is no constant behaviour.

**Expected behavior**
Order status should not be Processing until the final decision.

**Magento version**
2.4.1

**Plugin version**
8.1.1

**Screenshots**
![Screenshot 2022-11-16 at 09 51 04](https://user-images.githubusercontent.com/3583507/202133528-ec75e967-317d-4637-b45f-891e9dae2935.png)

![Screenshot 2022-11-16 at 09 53 29](https://user-images.githubusercontent.com/3583507/202134121-658ace5a-fd5f-420e-92a9-ccce7dd0192e.png)

![Screenshot 2022-11-16 at 09 55 21](https://user-images.githubusercontent.com/3583507/202134615-103a95f9-bad5-4862-99ba-8adc42308ca4.png)

![Screenshot 2022-11-16 at 09 55 45](https://user-images.githubusercontent.com/3583507/202134724-8a4e0e9c-754a-4d61-8538-ab7ed97b82bc.png)

**Comment by Morerice** [comment]
Hi @killoff,

Thanks for opening this issue. However, since this issue doesn't contain any specific reference to code and also because we will need the full psp reference to investigate, could you please create an internal ticket by sending an email to support@adyen.com? Please include a link to this issue. We are in close contact with our support team so that we can investigate this together.

If an issue within the module is found, we will link the pull request to this issue to make our fix visible.

Thanks,
Jean
Adyen

**Comment by killoff** [comment]
@Morerice ok, will do that.
