### ISSUE TITLE
[PW-7599] - Cronjob adyen_payment_cancel_expired_orders throws error

### ISSUE THREAD

**Issue by stephanie-ehrling** [Adyen/adyen-magento2#1867]
The cronjob adyen_payment_cancel_expired_orders throws the following error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'extension_attribute_payment_method.method' in 'where clause', query was: SELECT `main_table`.* FROM `sales_order` AS `main_table` WHERE ((`extension_attribute_payment_method`.`method` = 'adyen_pay_by_link')) AND ((`state` = 'new'))

**Magento version**
2.4.5-p1

**Plugin version**
8.11.0

**Comment by Morerice** [comment]
Hi @stephanie-ehrling,

Thanks for creating this issue. I've created an internal ticket to fix this. The plan is to use the `sales_order_payment.method` column, instead of this extension attribute that was removed in #1805

Thanks,
Jean
Adyen

**Comment by sensi-uros** [comment]
Hi! @candemiralp, @Morerice,

Is such loose filtering really ok? In our case, due to some custom 3rd party methods not updating state properly, updated version now tries to loop over 3 million orders each runtime and fails of course. But before cron worked perfectly fine. Maybe to somehow still filter payment methods we are targeting to prevent such issues?

Thanks,
Uros
