### ISSUE TITLE
Problem with 3DS 2.0 native implementation with magento headless

### ISSUE THREAD

**Issue by guillaumepigeon** [Adyen/adyen-magento2#1882]
**Describe the bug**
Hi,
we recently implemented adyen using the headless integration with magento. We use the drop-in component in the front end to render the payment form. We are now trying to implement the 3DS 2.0 functionality and are having issues with challenges. When we look at the data, it looks like everything should work. The resultCode is identifyShopper and we get an action object from the payments endpoint but when we call dropin.handleAction(action) nothing happens. We also saw that this data:  **authenticationData.threeDSRequestData.nativeThreeDS** is not being sent by the backend by default. Is it supposed to be set already in the module?  We are using API V69 and adyen web 5.30.0

**Expected behavior**
When we place an order we should receive the challenge to allow us to continue the checkout process.

**Magento version**
2.4.5

**Plugin version**
8.8.0

**Comment by guillaumepigeon** [comment]
Hello @candemiralp,

We see nothing in the console at the moment. We have no feedback or no errors. We tried having a `console.log()` in the `onAdditionalDetails()` method but it never reaches it. From what we've read in the documentation, this method is being called once we submit the result of the challenge and we suspect that since we are not receiving a challenge, we never submit any data. We also used the documentation you linked here in our implementation.

I hope that it gives you more insight. Let us know if you have more questions.

Thank you,
Guillaume

**Comment by candemiralp** [comment]
Hello @guillaumepigeon,

Thank you for your patience during our investigation. During this time we double checked the 3DS payment flow on the plugin with Adyen Web Components and it worked fine both in the headless and headed integrations.

As you mentioned in your previous comment, `onAdditionalDetails()` method is not reachable. This might indicate that you can't obtain the callback event from the drop-in and presents a buggy JS implementation of the drop-in. After checking your previous Github issue on the Adyen Web repository, I saw your `action` is a string instead of an action as @ribeiroguilherme suggested.

To tackle this conversion, we apply [this](https://github.com/Adyen/adyen-magento2/blob/4c12592facc9f9b550addd994f461dd98c67b5e3/view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js#L302) `Json.parse()`. Could you please try to convert this string into an object?

I am closing this issue since it is not directly related to the plugin and doesn't refer any part of the code. If you have further questions later, please don't hesitate to comment on this one.

Best Regards,
Can
