### ISSUE TITLE
Slow admin order generation with Point of Sale POS #1743

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#1912]
Please merge/open this issue : Slow admin order generation with Point of Sale POS #1743

**Comment by Morerice** [comment]
Hi @dronerdk,

Apologies for the delay. Since we are still not able to replicate this issue on our test environments and because we will need specific psp references to investigate further, it would be better if you opened an internal ticket with our support team. This can be done by sending an email to support@adyen.com.

If the issue is successfully identified and fixed, we will link the relevant PR to the original issue, which you linked above.

Thanks,
Jean
Adyen
