### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null at Encryption.createRSAKey

### ISSUE THREAD

**Issue by Mage2you** [Adyen/adyen-magento2#192]
I am having this issue with the plugin upon clicking on "place order" button.

`Uncaught TypeError: Cannot read property 'split' of null
    at Encryption.createRSAKey (adyen.encrypt.min.js:16)
    at Encryption.encrypt (adyen.encrypt.min.js:16)
    at UiClass.placeOrder (adyen-cc-method.js:157)
    at HTMLButtonElement.<anonymous> (knockout.js:3863)
    at HTMLButtonElement.dispatch (jquery.js:4624)
    at HTMLButtonElement.elemData.handle (jquery.js:4292)`

I debugged but I am not getting the issue.

**Comment by lancergr** [comment]
Hi @Mage2you 

This can be caused if you don't have a Test/Live CSE key configured in Magento in combination with the mode (Test/Live) that is selected.

Kind Regards,
Giorgos
Adyen

**Comment by Mage2you** [comment]
I checked the CSE key and environment mode . the settings are fine. I ran **composer require** command. Still recieving this error.

<br />
<b>Fatal error</b>:  Uncaught Error: Class 'Adyen\Client' not found in /home/techstag/public_html/dto/app/code/Adyen/Payment/Gateway/Http/Client/TransactionAuthorization.php:67

**Comment by Mage2you** [comment]
PLease ask for something before bluntly closing the issue.

**Comment by lancergr** [comment]
Hi @Mage2you 

The title of the issue is something different with the problem you are describing now.
It is helpful for the users of GitHub searching about this error to know that setting the CSE key in combination with test/live mode resolves this. That's why the issue was closed.

Regarding your next issue, the fact that Adyen\Client is not found means that the classes are not autoloaded.
By running composer require, you should have the php-api-library placed under vendor/adyen folder? Do you have this in your Magento?


Regards
Giorgos
Adyen
