### ISSUE TITLE
Deprecated Functionality: strcmp(): Passing null to parameter #2 

### ISSUE THREAD

**Issue by Nuranto** [Adyen/adyen-magento2#1926]
Magento 2.4.5-p1
Adyen 8.13.0

`Deprecated Functionality: strcmp(): Passing null to parameter #2 ($string2) of type string is deprecated in /var/www/html/vendor/adyen/module-payment/Helper/PaymentMethods.php on line 819`

Found on Adyen notifications overview backend page on a "OFFER_CLOSED" event.

**Comment by Morerice** [comment]
Hi @Nuranto,

Thanks for creating this issue. Based on our tests, the `$order->getPayment()->getCcType()` should never be null, even in the case when a payment is not finalized yet (which is why the `OFFER_CLOSED` webhook is eventually sent).

Could you provide us with the payment method that was used, which is ultimately resulting in this issue?

Thanks,
Jean
Adyen

**Comment by Nuranto** [comment]
Hi,

Payment method is Adyen / Paypal.

**Comment by Morerice** [comment]
Hi @Nuranto,

I was unable to reproduce this issue on my system. Is this something that is occurring on every paypal payment or does it only occur sparsely?

Regards,
Jean
Adyen

**Comment by Nuranto** [comment]
Hi @Morerice,

No, we have hundreds of payments with Adyen/Paypal, and only 6 cases with this error.

**Comment by Morerice** [comment]
Hi @Nuranto,

In that case I think it would be better if you open a ticket with our internal support team by sending an email to support@adyen.com so that we can go trough some logs, to try and identify the issue.

If a problem related to the plugin is identified, we will link the resulting PR to this issue.

Regards,
Jean
Adyen
