### ISSUE TITLE
Multibanco details not on success page

### ISSUE THREAD

**Issue by xgerhard** [Adyen/adyen-magento2#1936]
**Is your feature request related to a problem? Please describe.**
Hi there, we noticed when users select Multibanco as paymethod they get redirected to the Magento success page with details on how to complete their payment. We were wondering why these details are placed on the success page.
We fire events (order confirmation, tracking conversion pixels) since we assume the order is complete, but the order is still not paid yet (pending).

**Describe the solution you'd like**
User is redirected to Adyen or to a different page within Magento for payment details/instructions.

![mbancoc01a12a816c5d0d892c160895f6d8812](https://user-images.githubusercontent.com/13732765/215764426-8ee2e45a-e03c-4989-83f4-fd24694f85d5.png)

**Comment by candemiralp** [comment]
Hello @xgerhard,

Thank you for reaching out to us about your suggestion.

Multibanco is a voucher payment method that enables shoppers to complete their payments through different offline channels. By default, the first attribute after completing the order, presenting the voucher details to the shopper and wait for the actual payment action from the shopper. Since the response containing this information should be obtained by Magento, redirecting the shopper to an intermediate page is not possible.

Your Magento store will be informed via a webhook notification after the shopper completes the payment, which is the correct way to validate if the payment is successfully completed or not. Before, `Authorisation` webhook notification arrives, the state of the order is `Pending` or `Payment Review`. After processing this notification, payment status will be updated by the plugin. This case is valid for all of the payment methods supplied by Adyen.

You can re-open this issue if you need further information or have any other questions.

Best Regards,
Can

**Comment by xgerhard** [comment]
Hi Can, thanks for the answer and information. I understand the first part now, that the user has to be redirected back to Magento and not to a intermediate page. However then I still would suggest to not redirect the user to the success page, but a different (new?) page. Some tracking events are fired by just checking the url in for example Google Tag Manager, so not sure what a work around would be. Building a custom check for payment status at a success page doesn't sound logical to me either.

**Comment by candemiralp** [comment]
Hello @xgerhard,

Thank you for your comment and idea.

I understand the issue with GTM but your case is also valid for other payment methods (however, since most of the times, the payment goes through successfully, I believe you assume the order is paid upon the information on the success page without processing the notification). Actually, a payment 'technically' can fail after the notification. 

If you want to redirect shoppers to a different page for certain payment methods, you can achieve this by customising the plugin and specifing a different `returnUrl` for those payment methods. You can find the best practices for module customisation [here](https://developer.adobe.com/commerce/php/architecture/modules).

Unfortunately, since this case cannot be applicable to all of the merchants or is not solving a problem of the majority, we won't implement this solution in the context of the module.

Best Regards,
Can

**Comment by xgerhard** [comment]
Thanks for the info and consideration.
