### ISSUE TITLE
Bad displaying alternative payment methods

### ISSUE THREAD

**Issue by damienrogeonbic** [Adyen/adyen-magento2#1969]
Following differen discussion witg Adyen support team, here's an issue to fix.
Please let me know when you have visibility for fixing this. Thanks

**Describe the bug**
The displaying of alternative payment via plugin Magento is not as it should be

**To Reproduce**
1. Add product to cart
2. Go to payment step
3. See the alternative payment method Apple pay and:or Google pay
4. Select payment method : apple pay or google pay
5. The radio button is not displayed + the Apple pay logo and "Apple pay" title are too close  (see captures)

**Expected behavior**
Alternative payment method should be displayed as other payment method, meaning à radio button and a space between logo and text of the payment method.
We're about to activate Amazon pay soon and I think there will be the same issue.

**Magento version**
2.4.3 -p3

**Plugin version**
V 8.15.0

**Desktop (please complete the following information):**
All browsers : Edge, Chrome, Firefow, Safari…

**Smartphone (please complete the following information):**
All devices

![Affichage Apple pay](https://user-images.githubusercontent.com/126099748/220897204-51a3284d-c46a-43e9-9724-2aff49085325.png)
![Page paiement 1 (1)](https://user-images.githubusercontent.com/126099748/220897207-9412ac19-a5d1-48a3-8490-865ac4419838.jpg)
![Page paiement 1](https://user-images.githubusercontent.com/126099748/220897208-9ad099cd-5f6d-4a65-89e0-41984104036e.jpg)
![Page paiement 2 (1)](https://user-images.githubusercontent.com/126099748/220897210-e462c947-b3b3-4ff5-a6a2-0d786808601d.jpg)
![Page paiement 2](https://user-images.githubusercontent.com/126099748/220897212-96aafbbe-5d31-4323-bd6c-d10de83ab1b0.jpg)

**Comment by Morerice** [comment]
Hi @damienrogeonbic,

Thanks for opening this issue. From our end we don't have any specific styling done per payment method displayed. All our payment methods are rendered using the same html structure to ultimately enable our users to customize them as they please.

As you can see below, on a default luma installation, the payment methods are displayed in the same manner, with the same alignment.

![Screen Shot 2023-02-24 at 11 25 11](https://user-images.githubusercontent.com/11156828/221156165-23cd47a5-555d-4f9d-8ab9-45d697c57ba8.png)


Based on the provided screenshots you already have your own styling for the checkout page. Hence you should be able to add some further styling in order to show these payment methods according to your preference.

Regards,
Jean
Adyen

**Comment by damienrogeonbic** [comment]
Hi, 
Thanks for your fedback. I'll contact our provider to add what's needed.
We want to use amazon Pay with the plugin as well. Do you know if on a luma installation Amazon pay is displayed as you've just just shared ?

**Comment by Morerice** [comment]
Hi @damienrogeonbic,

Yes all our payment methods are displayed in the same format.

Regards,
Jean
Adyen
