### ISSUE TITLE
Checkout page gets stuck after login due to validation for internal request fails

### ISSUE THREAD

**Issue by andreusala** [Adyen/adyen-magento2#1978]
**Describe the bug**
Once I have logged in with my account from the checkout page and I go back to the purchase process, the page gets stuck because the server cannot process the request to access Adyen’s payment methods.

The request `V1/internal/carts/mine/retrieve-adyen-payment-methods` returns a 503 because internally it validates that the request is legitimate by checking the `form_key` field of the request but since it has a different user session they are not the same and it invalidates the request by throwing an exception. 

**To Reproduce**
1. Create a new customer if not exists yet
2. As guest, go to you storefront and add some product to cart
3. Go to checkout page
4. Fill your customer's email and wait for prompt your password
5. Just login with the credentials

**Expected behavior**
You will be redirected to checkout page again to continue checkout process

**Magento version**
[2.4.3]

**Plugin version**
[8.8.0]

**Comment by andreusala** [comment]
It seems to be related this issue [Formkey in window.checkoutConfig gets stale when logging in during checkout process](https://github.com/magento/magento2/issues/16020) also published on Magento backlog, isn't it? 

I've applied their solution and it is worked for me.

**Comment by Morerice** [comment]
Hi @andreusala,

Thanks for creating this issue and also looking further into it. Based on your comment it seems this is a magento platform issue, rather than one related to our plugin. Hence I'm closing this issue, since it's not related to our plugin.

For some extra info, this form key validation will probably be changed in our next major version (v9) which is due around H2 this year.

Regards,
Jean
Adyen
