### ISSUE TITLE
Warning: Undefined variable $result

### ISSUE THREAD

**Issue by tim-bezhashvyly** [Adyen/adyen-magento2#1982]
> Warning: Undefined variable $result in /app/nxtk5rtoi53wm/vendor/adyen/module-payment/Controller/Process/Result.php on line 225

Under some circumstances I am getting this exception. Apparently the redirect is not happening on line 222 and flow is continuing with `$result` variable being undefined. According to Adobe the best practice is to `return $this->_redirect(..)`. In this particular case it will ensure the flow is broken and line 255 is not reached.

**Magento version**
[e.g. 2.4.5-p1]

**Plugin version**
[e.g. 8.0.14]

**Comment by Morerice** [comment]
Hi @tim-bezhashvyly

Thanks for opening this issue and the linked PR. However we won't be merging the linked PR since this is tackling the result of the problem, not the origin of the issue itself. Since there are no reliable steps of how to re-create this issue and also because we may need to analyze some specific pspReference, could you please open a ticket with our internal support team by sending a mail to support@adyen.com?

We will update this issue if we identify the problem internally.

Regards,
Jean
Adyen
