### ISSUE TITLE
[PW-8342] Feature Request: There should be a way to delete/edit notifications from the adyen notifications grid

### ISSUE THREAD

**Issue by jordanvector** [Adyen/adyen-magento2#2008]
**Is your feature request related to a problem? Please describe.**
Hey Team, Currently in our backend we have this persistent message that we have 32 unprocessed notifications, that we cannot seem to get rid of unless we edit the database directly (which we would like to avoid). We have noticed that these unprocessed notifications fall into 2 buckets:
1. The message is of time REPORT_AVAILABLE which has nothing to do with magento and should be able to be deleted/editted via the notifications grid
2. Orders that required manual intervention, but were processed correctly outside of the typical flow.  We have a few messages saying that an invoice cannot be created for this order because one exists already or there was some sort of mismatch.  These in our case, orders have been fixed but the order notifications does not know that.

**Describe the solution you'd like**
It would be great if we could mark these notifications as processed or delete them all together. The reprocess action just errors currently on these sorts of messages

**Describe alternatives you've considered**
I guess we can go edit/delete these in the database directly, but I would like to avoid that if possible

**Comment by jordanvector** [comment]
For the first part, we implemented this PR to ignore unsupported notifications. Could you please check that PR the confirm if it solves the issue related to the first part?

Ah so this looks to be fixed since 8.15, but I am going to guess we had these notifications before this release, which is why they appear to still be lingering around.  Sounds like we just need to clean these up then 



For the second part, let me recap. Do you want to ignore/skip (or fail elegantly) the webhooks which try to create an invoice if the invoice is already created? I'll discuss your proposed solution (marking them as done or skipping them with a button on the UI) with our product manager.

I think failing elegantly would probably be good as long as we mark the notification as processed and doesn't continue to show up as a unprocessed notification.

**Comment by candemiralp** [comment]
Hello @jordanvector,

Thank you very much for confirming the first part. I believe, you can get rid of those notifications after a clean-up.

For the second issue, we made a small investigation. As you mentioned, webhook processor tries to process the webhook 5 times and if the `errorCount` is more than 5, this notification won't be picked-up again. However, we discovered that we are not marking those notifications as `done` after the fifth failing attempt. 

So, our proposal is marking the webhook notification as done in [this](https://github.com/Adyen/adyen-magento2/blob/9d6271a2686cfb55fbbff4b8f8f2f679cc65b9f8/Helper/Webhook.php#L567) function.

It is not possible to check the existence of the invoice for your flow, because that would lead to bigger issues. The regular flow assumes there is no invoice for auto capture payments and authorisation webhook creates and pays the invoice. The invoice and payment are completed outside of the regular flow in your case.

Could you please kindly inform us if the proposed flow works for you?

Best Regards,
Can

**Comment by jordanvector** [comment]
Yes I think this should work
