### ISSUE TITLE
Can't use Adyen in backoffice for CC

### ISSUE THREAD

**Issue by vahir2016** [Adyen/adyen-magento2#2013]
Hello,

In file "src/vendor/adyen/module-payment/etc/config.xml:49", can_use_internal had been set to false. We used to do CC with adyen from backoffice before.

Is it a normal change ? I haven't seen anything in logs that could help me to understand why it had been removed.

**Comment by candemiralp** [comment]
Hello @vahir2016,

Admin initiated card payments are now a separate payment method. Those functionality is offered under the MOTO (Mail Order Telephone Order) channel of Adyen. 

In order to use credit cards on the merchant initiated orders, you should enable and configure `Adyen MOTO` payment method. You can find the configuration fields on the plugin's configuration page and under the `Configure Payment Method` tab.

Best Regards,
Can
