### ISSUE TITLE
Multiple refused transactions of payment

### ISSUE THREAD

**Issue by paolobattistella** [Adyen/adyen-magento2#2098]
We have received multiple refused transactions of payment from an attacker with different IP addresses.

The steps of attacker are:
1) the attacker gets from checkout Adyen Keys needed to step
2) using Adyen SDK javascript the attacker is able to creates a payment token (for instance: https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens)
3) the attacker uses REST API MAGENTO:
POST V1/guest-carts (new cart)POST V1/guest-carts/{{cart_token}}/items (add item)
POST V1/guest-carts/{{cart_token}}/shipping-information (set address)
POST V1/guest-carts/{{cart_token}}/retrieve-adyen-payment-methods
POST V1/guest-carts/{{cart_token}}/payment-information (place order with payment token)
RESULT:
failure on Adyen  and extra fee from Adyen to Merchant

How is it possible to prevent these attacks?

**Magento version**
2.3.5

**Plugin version**
8.1.0

**Comment by fabioflebus** [comment]
Hello,
I will try to clarify the steps my collegue posted in this issue

> using Adyen SDK javascript the attacker is able to creates a payment token

with the JS card component the attacker can get the card tokenization (stateData), see this extract from adyen-cc-method.js
```JavaScript
this.checkoutComponent = await AdyenCheckout({...});
self.cardComponent = self.checkoutComponent.create('card', {...}).mount('#cardContainer');
let stateData = JSON.stringify(this.cardComponent.data);
```

> POST V1/guest-carts/{{cart_token}}/payment-information

this is the api for placing order in magento, in the body of the request the attacker can use the stateData obtained from step 1, for example
```JSON
{
    "billingAddress": {...},
    "paymentMethod": {
        "method": "adyen_cc",
        "po_number": "",
		"additional_data": {
			"stateData": "{\"riskData\":{\"clientData\":.\"eyJ2ZXJzaW9uIjoi...}",
			"guestEmail": "...",
			"cc_type": "VI",
			"combo_card_type": "credit",
			"is_active_payment_token_enabler": false,
			"number_of_installments": ""
		}
    },
    "email": "...",
    "cartId": "..."
}
```
In this step the magento module will send the request to Adyen api that will validate the card. The result is that the Merchant is charged with a fee for using the api and the attacker now knows that the card is valid or not (POST V1/guest-carts/{{cart_token}}/payment-information returns an error response, and in the body it is also specified that the card is not valid)

**Comment by peterojo** [comment]
Hi @paolobattistella and @fabioflebus!
Thanks for reaching out and creating this issue, there are a few assumptions from your comments that I would like to address.
1. First, card tokenization and state data are very different concepts: Tokenization means sending [specific parameters](https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens#set-parameters-to-flag-transactions) to Adyen's /payments API in order to save a reference (token) to a shopper's payment details for future use by the same shopper, the token is only then created **after** the payment has been made. State data here refers to the payload of encrypted data that the [Web Components SDK](https://github.com/Adyen/adyen-web) generates when a shopper fills in his/her payment details on your website, this data forms part of the original request that is sent to the /payments endpoint.
2. An attacker cannot use the [Web Components SDK](https://github.com/Adyen/adyen-web) to generate random state data "with different IP addresses" because one of the required fields for instantiating the `AdyenCheckout` component is the client key of the merchant's web service user, and the web address where the component will be mounted must already be white-listed for that web service user (see [here](https://docs.adyen.com/development-resources/client-side-authentication#allowed-origins) for more info on this) meaning that even if an attacker gets their hands on your client key, they cannot use it to mount the SDK component outside of your website.
3. With regards to the REST endpoints, the `cart_token` of course refers to the Magento ID for a [shoppers cart](https://developer.adobe.com/commerce/webapi/rest/tutorials/orders/order-add-items/), it has nothing to do with tokenization or state data. Our plugin is built to support merchants using Magento REST endpoints with their own custom PWA or SPA frontend. You will see from our [headless integrations docs](https://docs.adyen.com/plugins/adobe-commerce/adobe-commerce-headless-integration#place-order) that merchants are allowed to use the SDK to collect payment details from the shopper and send in Magento REST `/payment-information` endpoint. This is how the plugin is meant to work, and not a bug.

I understand that this doesn't solve your issue but hopefully you can see that your assumptions about the cause of the issue were not well informed.
I would recommend the following:
- Investigate further into where and how these attacks are **really** being generated, for example by inspecting the API logs and comparing legitimate requests with the fake ones.
- Could your Magento server or Adyen Customer account have been hacked? Look into your existing network security setup for any possible vulnerabilities that could allow for spoofing or DDOS attacks.

This issue will remain closed but feel free to open a new issue if you find a bug in our module.
