### ISSUE TITLE
Looking for increase or decrease authorize token payment amount

### ISSUE THREAD

**Issue by SyedWaqasNabi** [Adyen/adyen-magento2#2143]
I am looking for functionality where we can edit the order and create new order with amount greater or less than the last authorized amount.  I checked Adyen API and it has option to update the amount against the authorized token. Is this functionality available in the extension? Can you confirm it?

**Comment by candemiralp** [comment]
Hello @SyedWaqasNabi,

Could you please extend the use case and give an example for your case? Currently, Adyen supports authorisation adjustments but it is not supported by the plugin.

Best Regards,
Can

**Comment by SyedWaqasNabi** [comment]
Hi @candemiralp,

What we are are trying do we have 3rd party ERP system where order send from Magento to that system. Sometime we need to edit the order to add items or delete the items from the order in our ERP. It send the changed information to Magento and at that time we cancelled the order and create a new order but we want to use the authorization adjustment to extend the amount rather then user has to pay it again. I see in extension we have pay by link option which we are trying to use but we were just checking if this authorization amount adjustment thing can work or not.

**Comment by candemiralp** [comment]
Hi @SyedWaqasNabi,

Thank you for your answer and detailed explanation. Now, your use case is crystal clear.

As I mentioned before authorisation adjustment is not supported by the plugin, currently. Because, it is not in the regular e-commerce flow for the default use cases of the plugin and Magento 2. Also, it would affect the modifications for that payment (since the authorised amount has been adjusted). Due to those facts, we decided to step back for that feature.

However, you can still extend and customise the plugin to achieve this functionality. Please refer to [Pre-authorisation and authorisation adjustment
](https://docs.adyen.com/online-payments/adjust-authorisation/) docs page about the implementation of this feature.

Since this feature is not going to be implemented to the plugin, I am closing this Github issue. You can always reach out our support channels via support@adyen.com.

Best Regards,
Can
