### ISSUE TITLE
Call improper static function while executing notifications

### ISSUE THREAD

**Issue by pfortin-expertime** [Adyen/adyen-magento2#2163]
Notifications created by the webhook can't be executed, even manually when we retry from the back office (get the message "Issue occured while reprocessing the webhook notification!")

The issue is on line 182 of the Webhook helper, it's trying to call a static function:

`$webhookHandler = $this->webhookHandlerFactory::create($notification->getEventCode());`

 but the targeted function in the WebhookHandlerFactory is not static (line 68):

` public function create(string $eventCode): WebhookHandlerInterface`

![adyen-static](https://github.com/Adyen/adyen-magento2/assets/10864129/cca1536d-acb1-49ea-93a0-5f2e79ddcfc0)

![adyen-static-2](https://github.com/Adyen/adyen-magento2/assets/10864129/b6ac70c7-0f3d-4154-889f-022f27a20c1d)

**Plugin version**
[e.g. 8.20.0]

**Comment by Nuranto** [comment]
Same error after updating module from 8.19.1 to 8.20.0

**Comment by candemiralp** [comment]
Hello @pfortin-expertime, @demtaric and @Nuranto!

Thanks for raising this issue. A fix has already been created for this issue and we will release it as a hot-fix.

Best Regards,
Can

**Comment by demtaric** [comment]
@candemiralp Is it possible to change the order status, which stuck due to this error?
`Aug 17, 2023 10:45:11 AM Payment Review Customer Not Notified
The order failed to update: Deprecated Functionality: Non-static method Adyen\Payment\Helper\Webhook\WebhookHandlerFactory::create() should not be called statically in /var/www/html/vendor/adyen/module-payment/Helper/Webhook.php on line 182
Aug 17, 2023 10:45:11 AM Payment Review Customer Not Notified
Adyen HTTP Notification(s):
eventCode: AUTHORISATION
.....`

It tried 4 times and now order still in **_Payment Review_**
