### ISSUE TITLE
Failed Setup:Upgrade magento 2 command

### ISSUE THREAD

**Issue by XxXgeoXxX** [Adyen/adyen-magento2#2249]
**Describe the bug**
Magento setup:upgrade command failed with notification after upgrade plugin from 8.14.0(see attachments)

**To Reproduce**
The bug was reproduced only in our production environment. Bitbucket deployment works correctly for staging and locally it was not reproducible.

**Expected behavior**
The command was run without an error message

**Magento version**
Magento 2.4.5-p4

**Plugin version**
adyen/module-payment => 8.21.0 and 8.20.0

**Screenshots**
<img width="1403" alt="Знімок екрана 2023-10-03 о 08 45 09" src="https://github.com/Adyen/adyen-magento2/assets/44254165/4a0db1c6-1998-477e-ab8e-330504e5f1e6">
<img width="1403" alt="Знімок екрана 2023-10-03 о 08 45 37" src="https://github.com/Adyen/adyen-magento2/assets/44254165/9bc4ea23-879f-493f-94c7-b95069b70209">

**Comment by candemiralp** [comment]
Hello @XxXgeoXxX,

Thank you for raising this issue. However, we are unable to reproduce your issue. It seems like your production environment can't find the files [queue_consumer.xml](https://github.com/Adyen/adyen-magento2/blob/8.22.0/etc/queue_consumer.xml) and [queue_publisher.xml](https://github.com/Adyen/adyen-magento2/blob/8.22.0/etc/queue_publisher.xml). 

I would recommend checking those files and running commands again. If the issue is persistent, please send a support request to support@adyen.com.

Best Regards,
Can
