### ISSUE TITLE
[ECP-8822] Incorrect webhook processing URL when using Automated configuration mode

### ISSUE THREAD

**Issue by aweb3r** [Adyen/adyen-magento2#2379]
**Bug**
When using the "Automated" configuration mode, the incorrect webhook URL is saved in the MerchantAccount under Developers Webhooks.

**To Reproduce**
1. Go to Stores / Configuration / Sales / Payment Methods / Adyen Configure / Initial Setup
2. Select Configuration Mode "Automated"
3. Choose Environment
4. Fill Credentials
5. Click next
6. Choose "No, generate new username and password for me"
7. Fill Credentiaös
8. Click on 'Save Config'
9. See wrong URL-Path in your Merchant Account in : Developers / Webhooks / Your Webhook / URL : https://shopdomain/adyen/process/json
10. Click on "Test Webhook" and see "Test failed"

**Expected behavior**
https://shopdomain/adyen/webhook

**Magento version**
[2.4.6-p3]

**Plugin version**
[9.0.2]

**Comment by khushboo-singhvi** [comment]
Hello @aweb3r,

Thank you for bringing the issue to our attention, and for taking the time to submit a detailed report on GitHub. We appreciate your contribution to improving our project.

I wanted to inform you that we have acknowledged the bug, and it has been escalated to our internal tracking system. We aim to have a fix in place as soon as possible.

We will keep you updated on the progress, and once the issue is resolved, we'll notify you promptly. In the meantime, if you have any additional information or questions, please feel free to add them to the GitHub thread, and we'll do our best to address them.

Thank you for your patience and understanding.

Best Regards,
Khushboo
