### ISSUE TITLE
SEPA Bank Transfer - Misleading Content under Payment Method

### ISSUE THREAD

**Issue by Joelledes** [Adyen/adyen-magento2#2422]
*Describe the bug*
In our EU Magento store, using the adyen payment module, we offer our customers the SEPA Bank Transfer payment method. Under this payment method, there is copy that states 'Continue to create a new bank transfer payment. *You can use the details in the following screen to finalize this payment*.'
![image](https://github.com/Adyen/adyen-magento2/assets/150190363/77e79da4-0729-421f-8644-9b7c84c6433c)

However, this is not an accurate description of the UX. There is no 'following screen', the customer gets a normal 'thank you' order success screen  (same as any other payment method) and then an email with code to complete the bank transfer.

Adyen support has been completely unhelpful and simply said the SEPA redirects are buggy and suggested we don't use this payment method.

*To Reproduce*

In staging, we can test by selecting this payment method and completing order without having to enter any credentials, there is no following screen in staging or prod. We can only simulate customer's payment by Adyen admin (QA & Technical teams have permission to do this if need be).
1. Go to http://magstaging.wacom.com/ > Go to Belgium (EN) storeview
2. Add any product to cart, proceed to checkout
3. Select SEPA Bank Transfer as Payment Method - observe copy
4. Complete order - observe - no redirect to ‘following screen’ as specified in the above copy - poor ux - does inform customers of correct next steps

*Expected behavior*
I would like to see 1 of 2 outcomes:
1. A solution where the user does in fact get redirected to this supposed 'next screen' as communicated in the payment method copy coming from Adyen OR
2. A solution on how to edit this copy so we can accurately communicate next steps to our customers "To make the payment via bank transfer, you need to provide the reference number. You'll find this in your confirmation email." 

*Magento version*
Current: 2.4.3 (currently upgrading to 2.4.6 - go live in Jan)

*Plugin version*
8.6

**Comment by khushboo-singhvi** [comment]
Hey @Joelledes, Wish you a very Happy New Year!

Thank you for reaching out and bringing the issue to our attention. After thorough investigation, it appears that the problem you're encountering may be attributed to customizations on your end rather than a direct issue with the plugin.

I have extensively tested the flow, and it is functioning as intended in its default configuration. However, we understand that every system and setup is unique, and customizations can sometimes lead to unexpected behavior.

If you have any questions or need further clarification, feel free to let us know. 

Regards!
Khushboo

**Comment by Joelledes** [comment]
ok, thanks very much for your timely feedback!


Joelle Despins | Specialist IT Business Analyst

Wacom Technology Corporation

________________________________
