### ISSUE TITLE
[ECP-9154][ECP-9491] Excessive network usage while making a virtual purchase

### ISSUE THREAD

**Issue by embolden** [Adyen/adyen-magento2#2581]
**Describe the bug**
When placing an order for a virtual product adyen.js makes ~100 calls to each of dfp.1.0.0.html, fingerprintjs2.js, and risk.1.0.0.js.  This transfers 2.8MB over the network.  Purchasing a physical product makes ~6 calls on the same environment.

**To Reproduce**
Assuming a clean Magento 2 installation with only the Adyen plugin installed and a sample virtual product.
1. Add virtual product to cart
2. Go to checkout
3. Observe network tab

**Expected behavior**
I would expect that 1 call would be sufficient for these.

**Magento version**
2.4.6-p4

**Plugin version**
9.3.0

**Screenshots**
Sorry for the resolution - Github limits to 10MB.
https://github.com/Adyen/adyen-magento2/assets/1679978/0a04b624-5149-45c8-90c6-7adaadbc84a7

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.1.1 (23B81)
 - Browser: Chrome
 - Version: 123.0.6312.107

**Comment by candemiralp** [comment]
Hello @embolden,

Thank you for raising this issue. We've created an internal investigation ticket. 

Best regards,
Can

**Comment by candemiralp** [comment]
Hello @embolden,

We've successfully reproduced this issue. But considering the current priorities, we won't be able to provide a fix soon. However, as a temporary solution, you can disable risk data collection which triggers all of those calls.

Please add the following line to [these](https://github.com/Adyen/adyen-magento2/blob/main/view/frontend/web/js/model/adyen-checkout.js#L25) configuration parameters.

```
risk: {
    enabled: false
}
```

You will be informed once we find an elegant solution to this issue.

Best regards,
Can

**Comment by JamelleG** [comment]
Hello @candemiralp,

We are also experiencing the same issue. While we know there is a temporary workaround by disabling the risk data collection, do you have any updates on when a permanent fix might be available?

Especially given that Adyen v8 support/maintenance ends in January 2025 (https://github.com/Adyen/adyen-magento2?tab=readme-ov-file#support--maintenance).

**Comment by Januszpl** [comment]
@candemiralp I would also suggest to review module initialization process and abstraction, and what happens if from different reasons other parts of the code sets again new set of payment methods, as I'm not sure 100% if current handles it in optimized way. I also would like to note that at one point when using Webkul OneStepCheckout I got all Adyen payment methods (> 100) instead of initial 17 (I didn't have time yesterday to finish debugging it). I also saw some methods on page load being initialized twice (however, this could be due some customization on our side - I should have time to investigate that during next days). However, as I said I would say it's important to see if the Adyen module works properly when update list of payment methods few times as you may detect some issues earlier.

**Comment by candemiralp** [comment]
Hello @JamelleG,

Thank you for your patience. We have introduced a POC to this issue and looking forwards some pilot tests. Could you please share your insights on the PR #2770?

Best Regards,
Can
