### ISSUE TITLE
[ECP-9098] PayPal not working when T&C's are not checked

### ISSUE THREAD

**Issue by Axel29** [Adyen/adyen-magento2#2613]
**Describe the bug**
Paypal's popup loads indefinitely when the terms and conditions are required but not checked by the customer.

**To Reproduce**
1. [ADMIN] Create checkout T&C (_Stores > Settings > Terms and Conditions_)
2. [ADMIN] Make these T&C required (_Stores > Settings > Configuration > Sales > Checkout > Checkout Options > Enable Terms and Conditions_)
3. [FRONTEND] Select PayPal as a payment method
4. [FRONTEND] Click on the "PayPal" yellow button that opens the PayPal dialog that allows the customer to pay

**Expected behavior**
PayPal's website is loaded and the customer can finalize the order.

**Actual behavior**
* PayPal's website dialog is opened but the loader never ends.
* If the customer closes the dialog, checks the T&C checkbox and click again on the PayPal yellow button, nothing happens, he is forced to reload the page and restart the checkout process.

**Magento version**
2.4.5-p1

**Plugin version**
9.5.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome 
 - Version 124.0.6367.201 (Official Build) (64-bit)

**Additional context**
Tried disabling every other module and going back to the Magento_Blank theme, didn't change anything.
If the T&C are checked, the PayPal dialog loads correctly and the order can be placed.

Here's a video of the bug:

https://github.com/Adyen/adyen-magento2/assets/3015249/923a1d3e-fa0f-4ac0-89d1-a39f35e54aa5

**Comment by RokPopov** [comment]
Hi @Axel29

Thank you for reporting this issue. There was already a similar issue reported for GooglePay and ApplePay [here](https://github.com/Adyen/adyen-magento2/issues/2547). Altho the behaviour is different, we believe the underlying reason is the same for both issues. I am updating the internal ticket we created to investigate the issue with the additional information you reported. 

I will be closing the ticket as of now. For the progress, you can track the original reported issue.

Kind regards,
Rok

**Comment by Axel29** [comment]
Hi @RokPopov ,

Thank you for the update.
For your information, I tried the patch given in the other issue by [sarfarazbheda](https://github.com/sarfarazbheda) but it didn't work out.

**Comment by vunguyen10111995** [comment]
Hi anyone, do you have any updates?
