### ISSUE TITLE
Module compatibility with Upcoming changes to refusal reason

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-magento2#2670]
Based on this article: https://help.adyen.com/updates/upcoming-changes-to-refusal-reason-handling-on-card-payment-methods

I see that a change of the API is planned for 2024 with changes on the `resultCode`. This change obviously impacts this module and the @adyen-web module. 

Are the following modules compatible ?

- adyen-magento2 v9.6.0 or higher
- [adyen-web v5.65.0](https://github.com/Adyen/adyen-web/releases/tag/v5.65.0) or higher

I see that since version 5.65.0 of the adyen-web module, there is a risk that iDeal will no longer work on the test environment.

> Known issue: iDEAL does not work in the test environment if your TEST Adyen merchant account is not configured to use the new payment flow. You must first contact our Support Team to configure your TEST merchant account. LIVE accounts are not affected.

**Comment by candemiralp** [comment]
Hello @dimitriBouteille,

Our plugin is compatible with those changes. However, if you use any of `rawAcquirerResponse`, `refusalReason` and `resultCode` combinations to perform custom business operations, you might need to check your customisations.

According to re-implementation of Ideal payment method (details can be found [here](https://www.adyen.com/knowledge-hub/the-new-ideal)), your merchant account needs to be adjusted. So that, with the latest upgrade on the plugin, there won't be issuer selector on the checkout page and the shopper will be redirected to Ideal hosted payment page for issuer selection. Please reach out to Adyen support to adjust your merchant account for Ideal 2.0.

Best Regards,
Can
