### ISSUE TITLE
[ECP-9423] Missing configuration for some payment methods, exemple : kcp_creditcard, kcp_payco, kcp_naverpay

### ISSUE THREAD

**Issue by aelmizeb** [Adyen/adyen-magento2#2671]
**Describe the bug**
On our KR website we use the following payment methods : 
 - Credit Card via KCP (**kcp_creditcard**)
 - KakaoPay (**kakaopay**)
 - PayCo (**kcp_payco**)
 -  **kcp_naverpay**

The KakaoPay payment method work fine but the other not wok, I dont see a configurations for those methods on the module like the kakaopay, is it normal ?

We use GraphQL but not sure if that change something.

**To Reproduce**
1. Add the "**Credit Card via KCP**", or "**PayCo**" to Adyen activated methods
2. Activate the methods on the Magento config via script (activate via data patch adyen_kcp_creditcard, adyen_kcp_payco ...) 
3. See if work

**Expected behavior**
The methods must work as expected (like the old versions of the module)

**Magento version**
2.4.7-p1

**Plugin version**
9.6.0

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aelmizeb** [comment]
hello,

Any update on this request please ?

**Comment by candemiralp** [comment]
Hello @aelmizeb,

Apologies for the delayed response.

Thank you for raising this issue. We've created a ticket to implement `kcp_payco`, `kcp_creditcard` and `kcp_naverpay` on V9. 

Best Regards,
Can

**Comment by jonathanribas** [comment]
Hi @candemiralp, 
How can you guys disable payment methods on v9? Have you done a communication regarding this?
When is the deadline to have those payment methods on v9 please?

**Comment by candemiralp** [comment]
Hello @jonathanribas,

Actually, we haven't disabled the payment methods. But, it was a side effect of implementing separate payment methods project on V9.

The plugin had a loop to mount components for all of the payment methods returning from `/paymentMethods` response on V8. These payment methods were falling under the `adyen_hpp` payment method umbrella. The decision was separating them on V9 to follow Magento's best practices. So that, now all of the payment methods have their own facades in `di.xml`. 

However, this implementation comes with a downside of requirement for individual implementations of the payment methods. Initially, we checked the volume of the transactions going through all of the payment methods on the plugin and made a priority list. Those payment methods were all implemented in two iterations. Some payment methods didn't have any transaction for the given time period so that those ones might still be missing on V9. We are giving our utmost effort to keep the supported payment methods parity between V8 and V9.

I hope that explains the whole scenario. As I mentioned before, we have created a ticket to implement those 3 payment methods to V9 and this ticket will be handled according to current priorities.

Best regards,
Can

**Comment by jonathanribas** [comment]
Hello @candemiralp,

We appreciate your efforts and hard work on this module.

Regrettably, we are constrained to V8 without Level 1 Full Support until January 2024 due to the absence of certain payment methods. Level 3 Security support will continue until January 2025, but time is of the essence.

We kindly request your assistance in launching the missing payment methods on V9 before the end of this year. Your cooperation in this matter would be greatly appreciated.

Thank you for your attention to this matter.

**Comment by candemiralp** [comment]
Hello @jonathanribas,

Thank you for sharing your urgency about the missing payment methods. This task is currently in progress and will be released soon.

You can refer to [Supported Payment Methods](https://docs.adyen.com/plugins/adobe-commerce/supported-payment-methods/) page of the plugin docs. As a fall-back, I also would recommend checking [this](https://github.com/Adyen/adyen-magento2/blob/1db12b8fd18beb56dc9751123f6410d620a9de90/etc/frontend/di.xml#L27) line in the codebase for the payment methods list.

Best Regards,
Can

**Comment by jonathanribas** [comment]
Hi @candemiralp,

Thanks for the update, we are waiting for it!

It will also allow us to address https://docs.adyen.com/online-payments/co-badged-cards-compliance/#do-not-discriminate-between-card-products

Regards, Jonathan.
