### ISSUE TITLE
Order status update fails when Merchant reference changes

### ISSUE THREAD

**Issue by nola-adrien** [Adyen/adyen-magento2#2711]
**Describe the bug**
The order status is not updated when the order is "captured" by an another internal system when the capture method is Manual.

**To Reproduce**
1. Order is created in Magento
The webhook is properly set up, it updates the order status to "Authorised"
2. The order is exported to "SAP", (internal order management system)
3. SAP trigger the capture
The CAPTURE webhook is triggered but the Merchant reference has changed (SAP id probably instead of Magento Increment ID)
4. I get the adyen_notification but with the error : 
Order w/merchant reference 3546900 not found
So the status of the order is not updated.

**Expected behavior**
The order status should be updated to "Processing" as it is configured in the back office.

**Magento version**
2.4.7

**Plugin version**
adyen/module-payment 9.6.0 (with adyen/module/hyva-checkout)

**Screenshots**
<img width="716" alt="image" src="https://github.com/user-attachments/assets/74bf30ba-fd97-46ba-ae0b-9520d14ac890">

**Additional context**
I'm surprised the Merchant reference was able to be changed by SAP (I don't have access to this system, only Magento).
The issue comes from the function `processNotification()` in the helper `Helper/Webhook.php`
The merchant reference is used to fetch the order :
`$order = $this->orderHelper->getOrderByIncrementId($notification->getMerchantReference());`
Is it normal? 
Shouldn't you use the PSP reference to fetch the order or is there another way to fix this issue?

Thanks for your help.

**Comment by candemiralp** [comment]
Hello @nola-adrien,

Thank you for raising this issue. Plugin uses merchant reference or order increment ID intentionally instead of pspreference. Because, one order might have multiple payments (pspreferences) (ie. gift card partial payments). Even though, there is a field in the `sales_order` table where we save the pspreference, it doesn't cover the partial payment cases. So, the relation between partial payments and orders are made in `adyen_order_payment` table after processing the `AUTHORISATION` webhook.

Besides those statements, in theory, it's possible to query the orders with pspreference if the webhook processor can't find any order with merchant reference. In my opinion, it will increase the complexity of the webhook processor and the system will be more error prone.

The correct implementation on SAP side would solve this issue. Ideally, the capture API request's `reference` field should be identical to the merchant reference of the order. Since this issue is related to the faulty implementation of an external system and there is no other merchants facing/requesting the same behaviour, we've decided not to introduce a fix for this issue.

Best Regards,
Can
