### ISSUE TITLE
allowDS3 in magento 2 module

### ISSUE THREAD

**Issue by hugostarte** [Adyen/adyen-magento2#2756]
Hello, 
There seems to be a problem with the requests when we go through the Magento 2 module.
The module is in v71 and we still use allowDS3, normal? Shouldn't it use "nativeThreeDS": preferred ?
see: https://github.com/search?q=repo%3AAdyen%2Fadyen-magento2+allow3DS2&type=code

![image-4](https://github.com/user-attachments/assets/ed08444e-c0af-418e-85b0-04aeb84055dc)

Payments are currently blocked with us because the 3Ds popup is displayed but the content is not displayed inside. So I think it's related.

Thanks

**Comment by candemiralp** [comment]
Hello @hugostarte,

Thank you for creating this issue. We are aware of `allow3DS2` is deprecated and will be removed eventually. We already have a ticket to migrate it on the next major version. 

On the other hand, this property works in the same way of `nativeThreeDS` and `nativeThreeDS` is mapped internally in Adyen Checkout API backend to `allow3DS2`. 

If you have problems with displaying the content of 3DS2 pop-up, it could be related to something else. Since we expect clear guidance on reproducing the issue and code references with exception messages on the Github issues, I don't think this is a valid Github issue but rather a support case.

Could you please send a support request to `support@adyen.com` with your logs (located under `var/logs/adyen/*` directory on your server)? So that, our support engineers can investigate the issue carefully and provide you some guidance.

Best Regards,
Can
