### ISSUE TITLE
On df.js initialization page is scrolled to the top

### ISSUE THREAD

**Issue by denissdubinin** [Adyen/adyen-magento2#395]
**Magento version**: 2.2.6
**Plugin version**: 2.3.2
**Description**:
On mobile devices when `df.js` script initializes, after 1-2 seconds page is scrolled to the top. After debugging i found that scrolling is caused by `getJsFonts` function inside df.js. When user agent is mobile desktop, offsetHeight and offsetWidth options are calculated wrong. This happens on Android Chrome and Desktop chrome mobile emulator.

Recently i contacted adyen support but didn't get any position response regarding the issue. Ticket reference is **547850**.

**Video**: https://youtu.be/OL246PUdC7M - at the beginning of the video you can see that i copied part of a mentioned function, where bug exist. 

I don't know the reasons for that strange function that returns array with font names, but this causes a bug that is quite critical for my project.

**Comment by cyattilakiss** [comment]
Hi @denissdubinin ,

Thank you for the detailed issue, we will look into it asap.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @denissdubinin ,

In the checkout-api feature branch release (feature/checkout-api-rebased approx in 3 weeks or sooner) we are going to introduce our new checkout components for alternative payment methods (based on secure fields) and with these, the device fingerprinting won't be necessary on the merchant side anymore, because the components will handle it. I would suggest you to wait for that release and then update the plugin.

If you need it right now, you can remove the df.js on your own, it should still work and you won't experience the scrolling anymore. (Just use what you see in the referenced pull request #397)

Best,
Attila
Adyen

**Comment by denissdubinin** [comment]
@cyattilakiss what is the point if `df.js` file, if we can just disable it with no effect?

**Comment by RicardsRikmanis** [comment]
@cyattilakiss Just making sure, its safe to remove it for module version `2.3.2`?

**Comment by cyattilakiss** [comment]
Hi @denissdubinin ,

The df.js creates the device fingerprint that helps us to process a payment with a higher success rate, although it is not a mandatory field (only for ratepay). It means if you remove it from any version before the next release the success rate could be lower in specific cases when the fraud is high, but will still work. That's why I suggested to remove it for this short time period if the scrolling issue cannot wait and after our new release when we start using our new openinvoice components we can remove the df.js without any consequences.

Best,
Attila
Adyen
