### ISSUE TITLE
[PW-1480] Ignore the REPORT_AVAILABLE notification

### ISSUE THREAD

**Issue by rakotomagento** [Adyen/adyen-magento2#415]
**Magento version**: "magento/product-enterprise-edition": "2.2.2"
**Plugin version** :"adyen/module-payment":"2.2.0" (but not corrected in the latest version 3.0.0)
**Description**

When you suscribe to the same report on many Adyen accounts and receive notifications on daily basis that have the same file name, the first notification is well stored in `adyen_notification` table, but the following are ignore because considered as duplicates.

Technically, in order to determine if a notification is a duplicate, module is checking unicity in table `adyen_notification` on 3 fields:
- `pspreference` : <the file name> ex: payments_accounting_report_2019_03_04.csv
- `event_code` : REPORT_AVAILABLE (constant)
- `success` : <boolean> true if successful

Given that pspreference (containing filename) is not unique and is already in database, the module ignore the other account notifications

Report Notifications ignored when many account generate report with same file name.

Few solutions are possible to solve this : 
- on Adyen side, change the `pspreference` sent by making `pspreference` unique (e.g: by adding account id for exemple)
- on module, change the way notification duplication is checked for reports (by checking `reason`, that is an unique url to the file to be downloaded).

Regards,

**Comment by cyattilakiss** [comment]
Hi @rakotomagento ,

Thank you for the heads up, to be honest the plugin was not intended to handle notifications for reports only notifications for payments so we didn't test it this extensively. 

Since in the notification we send the merchant account id as well we could create a unique id for these reports (by concatenating the pspReference and the merchantAccountId) which we could save into the database. It means in your case the system wouldn't recognise it as a duplication. For this an if statement should be implemented if the event code is something like REPORT_* then we should handle it as described above.

I will create a ticket for this internally and going to modify it in the future or if you are willing to open a PR for this we would be really grateful for that :)

Best,
Attila
Adyen

**Comment by tnaber** [comment]
Hi @rakotomagento,

As we have restructured our webhook processing module this issue has been resolved. If the issue still persists for you let us know!
For now, I am closing this.

Cheers,
Titus
