### ISSUE TITLE
[PW-2029] Charged currency is incorrect

### ISSUE THREAD

**Issue by gigadesign1** [Adyen/adyen-magento2#456]
**Magento version**: 2.3.1
**Plugin version**: 2.4.0
**Description**
When I configure Magento to display a local currency, this currency is sent to Adyen as the currency the customer has to complete the payment with.

This behaviour is different than other (built in) payment providers in Magento.
Magento itself also displays a notice that the currency that the customer will be charged for will be different:
![Schermafbeelding 2019-06-11 om 13 27 51](https://user-images.githubusercontent.com/1337445/59268587-50f33f80-8c4d-11e9-895f-4abf1b599f8e.png)
![Schermafbeelding 2019-06-11 om 13 28 39](https://user-images.githubusercontent.com/1337445/59268594-551f5d00-8c4d-11e9-8130-ca874a0f4a46.png)

If I complete this payment with a payment method provided by the Adyen plugin, the customer will be charged for £23.98 instead of €25.94

**Comment by cyattilakiss** [comment]
Hi @gigadesign1 ,

Can you please show me (screenshot or just a path) where do you set the currency, or maybe even better if you can just show me how the currency is retrieved to be the one that you want it to be sent to Adyen. Currently we use the quote to retrieve the currency. `$this->quote->getCurrency();` in the CheckoutDataBuilder.php

Thank you in advance,
Attila
Adyen

**Comment by gigadesign1** [comment]
Hi @cyattilakiss,

I think it should be `$this->quote->getBaseCurrency();` and `$this->quote->getBaseGrandTotal();`.

We have set `currency/options/base` to EUR and `currency/options/allow` to AUD,CAD,CHF,DKK,EUR,GBP,SEK,USD

According to the notice that Magento adds to the checkout, I would say that the transaction for this order should be in the base currency and not in the display currency.

**Comment by cyattilakiss** [comment]
Hi @gigadesign1 ,

Let me discuss it internally, I will get back to you soon.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @gigadesign1 ,

Currently the plugin uses only the display currency and our current merchants are using the plugin as it is. Although we understand that there are exceptions and merchants who wants to charge their customers in the base currency because of the accounting or other financial reasons.

The solution could be a setting in the magento admin where merchants can indicate which currency they want to use during the api calls to Adyen. 
It can be added here: https://github.com/Adyen/adyen-magento2/blob/develop/etc/adminhtml/system/adyen_required_settings.xml#L70

In the https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Data.php a new function should be created which retrieves the currentCurrency based on the configuration that we have just added in the previous step. (We already have a function like this in the https://github.com/Adyen/adyen-magento2/blob/develop/Helper/PaymentMethods.php#L289 so this needs to be removed and all replaced with the new function where it was used)

Also anywhere else in the plugin where we use the `getOrderCurrencyCode` or `getQuoteCurrencyCode` they need to be replaced by the new function.

We are going to schedule later it but if you can create the PR based on my notes above you can speed up the process :) 

Best,
Attila
Adyen

**Comment by ebaschiera** [comment]
Hi,
I agree with @gigadesign1 , payment gateway should receive payment requests in base currency, not frontend currency. That's a Magento best practice and the only documented one.
It's Adyen's decision not to follow that rule.

We ended patching the module on our websites :)

-Ermanno

**Comment by cyattilakiss** [comment]
Hi @ebaschiera ,

Adyen provides a lot of payment methods which are based on not just the country where these are available, but also the currency in which these are available. It means that since a webshop has only 1 base currency then it would only support payment methods in that 1 currency. I will give you an example for this: 

I have a webshop with the base currency in HUF, but EUR is also available. I have a customer from NL who wants to use iDeal which is not available in HUF but in EUR. In this case even if the customer sees the currency EUR and has the country NL, iDeal still won't be available since the webshop sends the base currency HUF and not EUR. (TBH it happened a lot with me personally and gave me a lot of headache as a customer)

Because of this reason we follow the current practise but because we see that this can be an issue for some merchants we will offer the setting which I just declared in my previous comment. I hope with this approach everyone can benefit from the plugin :)

Best,
Attila
Adyen

**Comment by ebaschiera** [comment]
Thanks @cyattilakiss for clarifing Adyen's point of view. It makes sense.
Yeah, the setting you mentioned would be very welcome.

Thanks!
-Ermanno

**Comment by gigadesign1** [comment]
Hi @cyattilakiss,

The base currency can be configured in website scope in Magento.

So it's still possible to use HUF and EUR as seperate base currencies if you have two websites with the different currencies configured.

![Schermafbeelding 2019-07-22 om 12 29 02](https://user-images.githubusercontent.com/1337445/61626014-657b1c80-ac7c-11e9-90a1-9a93737165ad.png)

However, the setting you mentioned could be a good solution to support backwords compatibility for clients that rely on the display currency to be charged to the customer.

**Comment by charleskj** [comment]
This is still an issue

**Comment by edroberts** [comment]
Why is this flagged as an 'enhancement'? This is a design flaw and needs to be fixed.

**Comment by xavierojeda** [comment]
Still having this issue as well.
Definitely a bug that needs to be sorted as it should only take the Default Display Currency as the currency to charge in.

**Comment by kesonno** [comment]
Hi @floorjubbega could you say if there is an ETA for this?

Thanks!
Gennaro

**Comment by kesonno** [comment]
Ok I've discovered now that exist a PR, alredy merged: https://github.com/Adyen/adyen-magento2/pull/851

Waiting for 7.0.0 to be relased then!

Thanks
Gennaro

**Comment by acampos1916** [comment]
@kesonno that’s right, in #851 we include a wrapper to get the base or display amount and currency depending on a config value. All feedback is welcome.

Ángel
