### ISSUE TITLE
Hosted Payment Page missing in settings and in checkout

### ISSUE THREAD

**Issue by Beagon** [Adyen/adyen-magento2#460]
**Magento version**: 2.2.8
**Plugin version**: 4.2.1
**Description**
For a client we have upgraded the Adyen module from 4.1.1 to 4.2.1, however all the Hosted Payment Page settings are now gone.

I've found that some settings are now under "Alternative payment methods" but most of the settings I just can't seem to find in the Magento Admin.

It appears this has happened on 4.2.0 since that changed a whole lot about the adyen_hpp implementation.

**Comment by cyattilakiss** [comment]
Hi @Beagon ,

Yes, we renamed the Hosted Payment Page to Alternative Payments because our goal is to implement more and more payment methods via direct API instead of the HPP. The settings that has been removed were removed because now with the checkout implementation it didn't add any value.

If you have any suggestion, if there is a setting that you would need but we have removed we can discuss it and if it is indeed necessary we can make a patch for that.

Best,
Attila
Adyenj

**Comment by Beagon** [comment]
Hi @cyattilakiss,

It would be nice to know where for example my Skin codes now go since we have a different skin per storeview. It would also be really nice if this was documented in a release note, I have been trying to find it in the changelogs but it seems to be non-existent.

Right now the only thing I can configure is the following:
![image](https://user-images.githubusercontent.com/2945583/59430895-b7aa6180-8de3-11e9-983e-66bee20db3de.png)

And no HPP methods show up in the checkout at this moment.

**Comment by cyattilakiss** [comment]
Hi @Beagon ,

Which payment methods did you use with HPP?

I confirmed it with the core team that now it is not possible to customise the HPP with the checkout API integration, instead you can customise your own checkout which leads to a better user experience and less redirects.

It can also be that you are just redirected to the HPP because there are some data missing from the request but by default it would have been a direct API integration.

Thank you for the feedback about the documentation I will create a task for that in our team board.

Best,
Attila

**Comment by Beagon** [comment]
Hi @cyattilakiss,

We've used the following: Klarna, Bancontact, EPS, iDEAL, Sofort, AfterPay, Gifcard, Generic Giftcard, PayPal, MasterCard, VISA, GiroPay, American Express.

We were using the HPP as our integrated payments options in the checkout which didn't lead to any redirect and just loaded in the HPP options as payment options in the checkout.

 For now I've reverted back to a version before this change since it's not clear yet what we should do to comply with the new way of customizing your checkout. We've tried to look at this documentation https://docs.adyen.com/checkout/ but this only talks about implementing this yourself and not what to do if you are using the Magento 2 Module.

Greetings,

Robin

**Comment by cyattilakiss** [comment]
Hi @Beagon ,

Can you please write an email to the support@adyen.com email address with this whole thread copy pasted? They are going to help you out with all questions that you may have regarding to this version of the plugin and the direct integration.

Also just to answer briefly:

"We've used the following: Klarna, Bancontact, EPS, iDEAL, Sofort, AfterPay, Gifcard, Generic Giftcard, PayPal, MasterCard, VISA, GiroPay, American Express."
Card payments are now handled by the checkout card component which let's the users enter their card details on your checkout page instead of redirecting to HPP. This card component handles the MasterCard, VISA, GiroPay, American Express and Bancontact from your list.

The Klarna integration is still a redirect which redirects to a non configurable Klarna hosted page.

iDeal is now handled by the iDeal component, basically you can choose from a select box the bank that you have and click place order.

Afterpay is handled by the AfterPay component, instead of entering the required details on a HPP users can enter their details on your checkout.

Gifcard, Generic Giftcard, PayPal are still redirects.

I hope this helps, but please contact support they will give you more information.

Best,
Attila
Adyen

**Comment by requix** [comment]
Hi @cyattilakiss,

We faced with the same issue.
Magento version: 2.2.8
Plugin version: 4.2.1

After upgrade, all HPP methods were not visible on checkout page.
Info from error.log

[2019-06-21 05:27:27] AdyenLoggerTest.ERROR: 010: Not allowed {"is_exception":false} [] 
[2019-06-21 05:27:27] AdyenLoggerTest.ERROR: The Payment methods response is empty check your Adyen configuration in Magento. {"is_exception":false} []

Adyen support added additional role to our webservice user and the issue was resolved.
All HPP methods are visible now.

However there are many questions about how it works now. Many HPP settings were gone and now it's not clear how to set up them. For Klarna we don't need gender, dob and telephone fields (we use additional fields in checkout for that). But we can't disable them from magento admin. Could you add some notes about how to do these changes?

![Screenshot 2019-06-21 at 10 31 57](https://user-images.githubusercontent.com/5894713/59909524-286b0280-9410-11e9-9d74-6f7a5e78c0d4.png)


Skin code was removed from settings as well. Does it mean we don't use Skin for HPP methods?

Agree with @Beagon, that there is nothing in documentation about these changes and about new way of customization. Another problem that all of these issues reproduced only in Production mode. In Test mode was everything fine.
