### ISSUE TITLE
Question Feature Downpayment

### ISSUE THREAD

**Issue by omerzs** [Adyen/adyen-magento2#462]
is there any possibility 
to  create downpaymnet via reoccurring payments /split invoice payment

**Comment by cyattilakiss** [comment]
Hi @omerzs ,

Since we are storing the token in billing agreement or vault (based on your settings) it is possible to write your own logic around it and ask for a downpayment at first, store the token and when the order is delivered you can use the token to charge your customer for the rest of the amount.

I hope it helps.
Best,
Attila
Adyen
