### ISSUE TITLE
Payment methods disappeared after upgrading to 4.3.0

### ISSUE THREAD

**Issue by bjarn** [Adyen/adyen-magento2#498]
**Magento version**: 2.3.2
**Plugin version**: 4.3.0
**Description**

We upgraded the module from version 4.0.3 to 4.3.0 and the payment methods completely disappeared from the checkout.

The following exceptions started to occur:
`[2019-08-09 13:55:50] AdyenLoggerTest.ERROR: 010: Not allowed {"is_exception":false} []
[2019-08-09 13:55:50] AdyenLoggerTest.ERROR: The getConnectedTerminals response is empty check your Adyen configuration in Magento. {"is_exception":false} []
[2019-08-09 13:56:19] AdyenLoggerTest.ERROR: 901: Invalid Merchant Account {"is_exception":false} []`

We tried to write a plugin to temporarily fix this issue by disabling the getConnectedTerminals function when the POS payment method has been disabled. But this did not work, as the getConnectedTerminals exception changed to:
`
[2019-08-12 08:07:15] AdyenLoggerTest.ERROR: The Payment methods response is empty check your Adyen configuration in Magento. {"is_exception":false} []`

This was the workaround we tried as it seemed there was no check in the adyen module to check if the POS method was enabled or not.
`    public function aroundGetConnectedTerminals(AdyenPaymentMethods $paymentMethods, callable $proceed)
    {
        if ($this->helper->getConfig('payment/adyen_pos_cloud/active')) {
            return $proceed();
        } else {
            return [];
        }
    }`

**Comment by cyattilakiss** [comment]
Hi @bjarn ,

TBH I don't really see any changes between 4.0.3 and 4.3.0 that should cause this issue so I assume that there is a configuration issue on your Merchant account.

At first I would suggest to disable the POS payment method in your Magento admin Adyen plugin settings because then the getConnectedTerminals function won't be triggered.
- If that does solve your issue then probably a wrong Merchant Account was set up in your Magento admin in the Adyen plugin. 
- If it doesn't solve the issue then probably since we moved to checkout api integration then you don't have the checkout role enabled in your Merchant account.

I think the fastest way to solve it is to contact our support team: support@adyen.com and they are going to check your merchant account's permissions and are also able to check the logs to see what went wrong. If something went wrong on the plugin side then they are going to redirect you to us after they investigate the issue.

Please include your log files in the email. If it is possible please clean them at first and then go to your checkout - with this approach it will be easier for us to spot the issue.

Best,
Attila
Adyen

**Comment by ryanpalmerweb** [comment]
Hi Bjarn,

Were you previously using HPP? 

We had the same issue as this has been deprecated for the new API

In our case, error 010 referred to the fact that we had to sign some documents in order to be allowed to use the new API.

Thanks,
Ryan
