### ISSUE TITLE
Fatal error: Class 'Adyen\Client' not found in magento2\app\code\Adyen\Payment\Model\Api\PaymentRequest.php on line 91

### ISSUE THREAD

**Issue by mpullmann** [Adyen/adyen-magento2#52]
Fatal error: Class 'Adyen\Client' not found in magento2\app\code\Adyen\Payment\Model\Api\PaymentRequest.php on line 91

What is 'Adyen\Client' and where is it defined at?

**Comment by rikterbeek** [comment]
Hi @mpullmann,

Best to install the module through composer because it has a dependency to the php-api-libarary repository. this decency is defined in composer see:
https://github.com/Adyen/adyen-magento2/blob/develop/composer.json#L25
The php-api-library can be found here https://github.com/Adyen/adyen-php-api-library
But if you use composer this will be installed automatically for you.

Regards,
Rik
Adyen

**Comment by mpullmann** [comment]
@rikterbeek Oh, thanks :+1:
