### ISSUE TITLE
Oneclick agreement doesn't work - cardBin missing from response

### ISSUE THREAD

**Issue by omarmohssen** [Adyen/adyen-magento2#530]
Magento version: 2.3.2
Plugin version: 4.3.0
Description

- Disable vault from CreditCard API integration > Vault Enabled > No

- Enable Oneclick agreement from Stored Payment Methods - Requires Adyen Credit Card > Enabled and Agreement Type > Oneclick

- Login from the frontend and proceed with checkout

- In the payment step select credit card and choose to save for next payment

**Expected result** : the order is placed and the payment agreement is saved in paypal_billing_agreement and displayed as a new option for the next checkout

**Actual result**: the order is placed but no payment agreement is saved in paypal_billing_agreement and no saved payment option appears in the next checkout

**Note**: Oneclick agreement should allow recurring payment for the saved card requiring the user to fill the CVC. Currently only vault can handle recurring payments but this will not ask for CVC.

Technical details:
Adyen\Payment\Model\Billing\Agreement (using the DB table _paypal_billing_agreement_) is not being saved on order place due to the missing parameter cardBin in the payment response although this parameter doesn't seem to be necessary for saving but it is checked for being present in the response in order to save the agreement:
adyen/module-payment/Model/Billing/Agreement.php:182

**Comment by cyattilakiss** [comment]
Hi @omarmohssen ,

This looks like a configuration issue in the customer area regarding your merchant account in the "API and response" -> "Additional data settings" tab.

Don't you get any logs in your logs/adyen folder regarding this? 
There should be some because of this line: https://github.com/Adyen/adyen-magento2/blob/42c7908fadfcce0e66bb85820c67241a391e588b/Model/Billing/Agreement.php#L191

If you can find it in your logs, could you please contact our support team via: support@adyen.com they are more than happy to set the correct additional data settings for you.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @omarmohssen ,

Is this issue still unresolved?
I will close this issue now, but if you still need some help fell free to reopen it.

Thank you in advance,
Attila
Adyen

**Comment by enl** [comment]
Useful link for anyone looking for answers: https://docs.adyen.com/plugins/magento-2/stored-payment-methods
