### ISSUE TITLE
Urgent | Broken 3d secure due to requestOptions

### ISSUE THREAD

**Issue by ruthgeridema** [Adyen/adyen-magento2#537]
**Magento version**: 2.3.2
**Plugin version**: latest
**Description**
[PW-1737] Add idempotency key (#531) breaks 3D secure payments. It returns '3d secure not valid' while the 3d secure IS valid.

Logs are not helping to solve this issue. If we remove the additional $requestOptions the checkout works as expected

**Comment by cyattilakiss** [comment]
Hi @ruthgeridema ,

Thank you for raising the issue, I'm checking it immediately.
Can you help me with providing, which test case breaks?
3DS1 or 3DS2?

Thanks,
Attila
Adyen

**Comment by ruthgeridema** [comment]
Hi @cyattilakiss ,

[2019-10-09 11:13:07] AdyenLoggerTest.ADYEN_RESULT: 3D secure is active {"is_exception":false} []
[2019-10-09 11:13:07] AdyenLoggerTest.ADYEN_RESULT: Customer was redirected to bank for 3D-secure validation. {"is_exception":false} []

**Comment by cyattilakiss** [comment]
Thanks.
We found the issue, working on the hotfix right now.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @ruthgeridema 

You can find the hotfix in the https://github.com/Adyen/adyen-magento2/releases/tag/4.5.4
Thank you again for raising the issue.

Best,
Attila
Adyen

**Comment by ryanpalmerweb** [comment]
Hi Everyone,

Just to follow up on this, we encountered this issue and applied the fix, however a number of orders are still failing and it looks like this is because the failed order increment id's which have been logged within Adyen are being reused.

We are currently in the process of manually correcting quotes with a reserved increment id which has failed

Thanks

**Comment by cyattilakiss** [comment]
Hi @ryanpalmerweb ,

The order id which has failed during payment should be skipped and a new increment id should be used for each new payment attempt. I just tested this specific scenario and is working on my test instance.

What do you think how it can be that Magento assigns old order ids as new increment id to new orders?

Maybe I miss something, please let me know if you have more information or further questions.

Best,
Attila
Adyen

**Comment by ryanpalmerweb** [comment]
Hi Attila,

I think this is specifically for orders which had the broken 3D secure issue, I'm not sure on the exact audit trail but we can confirm that the order ids which were failing yesterday have been re-used by Magento, however the database has not been rolled back or anything like that

Our solution is to add the order numbers which failed yesterday to the following query :

UPDATE magento2.quote SET reserved_order_id = NULL WHERE reserved_order_id IN ( order numbers go here )

Perhaps there are other factors to this, but thought the information would be useful on this thread if anyone else encounters it.

Thanks

**Comment by cyattilakiss** [comment]
Hi @ryanpalmerweb ,

Thanks for sharing it :)
Let me know if it continues because then this is probably not just a temporary issue after applying the patch but something that we need to take care.

Best,
Attila
Adyen

**Comment by ryanpalmerweb** [comment]
Hi Attila,

Unfortunately it seems that the issue wasn't just isolated to yesterday, as we've managed to replicate it.

Please try the following to replicate the issue using Magento 2.3.2-p2 and Adyen 4.5.4, for a checkout with CSE and also PayPal enabled :

1 - Put some items in the basket and go to the checkout payment section
2 - Choose to pay by card, use an invalid number which validates (e.g 4111 1111 1111 1111)
3 - Place order so that you get the message "Payment Refused"
4 - Now switch the payment method to PayPal
5 - Click place order - instead of being redirected to PayPal you will get "Payment Refused" again

Thanks,
Ryan

**Comment by cyattilakiss** [comment]
Hi @ryanpalmerweb ,

We are checking this case, gonna get back to you when we have a solution for this.

Best,
Attila
Adyen

**Comment by ryanpalmerweb** [comment]
Hi Attila,

Were you able to replicate the bug? 

We have had to disable PayPal via Adyen and are using a direct integration instead for the time being.

Thanks,
Ryan

**Comment by cyattilakiss** [comment]
Ho @ryanpalmerweb 

Yes, we were. We decided to reduce the scope of the idempotency key to the adyen_hpp payment methods for now as a quick fix, and then we will have time to standardise the card payment and the alternative payment method flows because currently it is hard to handle the 2 different flows.

We still need some time to validate this quick fix but we will release it as soon as possible.
Sorry for the inconveniences and thanks for raising the issue again.

Best,
Attila
Adyen

**Comment by ryanpalmerweb** [comment]
Hi Attila,

The update has been pending review for a week now, and we are frequently having problems with customers being unable to pay, preventing high value orders.

It's quite a severe issue to leave open - has there been any movement? 

Thanks,
Ryan

**Comment by cyattilakiss** [comment]
Hi @ryanpalmerweb ,

We have just released version 5.0.0 with the fix for your issue.
Let me know if you face any issues regarding to this.

Best,
Attila
Adyen
