### ISSUE TITLE
House Number split logic doesn't support non-EU addresses

### ISSUE THREAD

**Issue by moloughlin** [Adyen/adyen-magento2#554]
**Magento version**: 2.3.2
**Plugin version**: 4.3.0
**Description**

\Adyen\Payment\Helper\Data::formatStreet uses a naive regex to split an entered street field into it's `house_number` and `street` components. 

`/((\s\d{0,10})|(\s\d{0,10}\w{1,3}))$/i`

This will match on typical EU addresses (e.g. `Simon Carmiggeltstraat 6-50`), but not on US/AU/CA/etc addresses (e.g. `123 Fake Street`) since the regex expects whitespace to precede the number component.

I wonder if this is something that needs to be a little smarter - maybe pass in the selected country code and determine the ideal regex to use for that country? Or keeping it simple, just match `[^\s]\d{0,10}` instead to cover the case where the number component is at the start of the string?

**Comment by cyattilakiss** [comment]
Hi @moloughlin ,

This question pops up every once in a while internally as well. In the last iteration we decided to find the house number only for some EU countries where we require this specific field.
The issue is mostly with the non EU countries as you mentioned because it can happen that there are numbers leading and trailing the address when with a simple regex we simply cannot decide which one is the house number and the street name.
Right now we are going to keep it as it is but if you have any good idea and maybe you can also create the pull request we are more than happy to give feedback and review the code.

Best,
Attila
Adyen
