### ISSUE TITLE
Release 5.0.0 reports wrong version in backend.

### ISSUE THREAD

**Issue by adrianiacob** [Adyen/adyen-magento2#567]
**Magento version**: 2.3.3
**Plugin version**: 5.0.0
**Description**
Release 5.0.0 reports a wrong version in the backend => 4.5.4, due to etc/module.xml not being updated to 5.0.0. This can cause confusion.

**Comment by cyattilakiss** [comment]
Hi @adrianiacob ,

Thank you for raising the issue, I created a fix for this. Instead of bumping the setup_version all the time even if we don't have any upgrade script to run, we use from now the composer.json version.
It is not a good practise to bump the setup_version if no upgrade script is available that is the reason why we decided to follow this approach instead.

Best,
Attila
Adyen

**Comment by adrianiacob** [comment]
@cyattilakiss  sure even better if getting from composer.json for backend view. Mentioned the setup_version bump because I tracked it to that in the get logic.
