### ISSUE TITLE
Empty cart when clicking 'back' on Adyen Payment page

### ISSUE THREAD

**Issue by asirovica** [Adyen/adyen-magento2#62]
**Not sure if this is a bug, a new feature or something that's not possible:**
When you get to the Adyen Payment page from the checkout and click 'cancel', you go back to your cart with the products still inside. However, when clicking the 'back' button of your browser, you get an empty cart. 

You would expect the same result (a cart with your selected products) when clicking the 'back' button in your browser.

**Comment by rikterbeek** [comment]
Hi @asirovica,

When you press the back button in the browser we can't control the logic of the previous page. This is something magento handles. I think the best is to raise this issue at https://github.com/magento/magento2

Groet,
Rik

**Comment by TommyKolkman** [comment]
@rikterbeek I know it's is a closed item, but just to verify, because our customer is asking for this again: would opening the payment issuer page in a new window help? I'm not sure how to fix it, from within Magento they redirect us back here.

**Comment by amenk** [comment]
Please reopen. The magneto standard PayPal integration does not suffer from this problem. It might not be a magento core issue.

**Comment by kweij** [comment]
I agree with @amenk that this behaviour might better be part of the Magento 2 integration of the Adyen payment provider.

Magento does not provide off-site payment methods (such as iDeal) by default so it doesn't need to handle the unhappy-flow using the back-button. The back-button flow is part of the iDeal payment flow which is provided by the Adyen integration module.

I also agree with @rikterbeek that this may require some changes to Magento (in the form of a plugin/preference of other solution) but since everyone using the Adyen Magento 2 module needs to separately address this issue, it might better be a part of this module.

If I can get the budget to find a solution for this issue I will share it, but the integration of Adyen into Magento 2 is not my specialty. Any help is appreciated :)

**Comment by amenk** [comment]
@rikterbeek is there any news on this? We had a similar problem with Customweb extension, who were able to solve this.
Or is in current versions the problem solved?

**Comment by amenk** [comment]
Can this be reopened or shall we create a new issue? We can reproduce the problem still in Klarna und giropay payments via Adyen.
