### ISSUE TITLE
constructor argument calling order

### ISSUE THREAD

**Issue by imrankln** [Adyen/adyen-magento2#626]
**Describe the bug**
Calling of `array $data = []` in the middle of constructor throws exception, "class not found".
If we call the above code at the end of constructor argument, everything works fine.
Following two files need modification:
Block/Redirect/Redirect.php
Block/Info/PaymentLink.php

**To Reproduce**
we faced error "Class not found" on production mode and frequency is rare.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Pull request #625 has been created.

**Comment by cyattilakiss** [comment]
Hi @imrankln ,

Thank you for raising the issue, for the detailed report and for the PR which fixes it. The PR is already merged. I can only say good job! :)

I will close this issue since your PR is already merged and it's going to be released in the next couple of days.

Have a great day!
Best,
Attila
Adyen
