### ISSUE TITLE
[BUG] Payment Methods do not match cart total amount

### ISSUE THREAD

**Issue by GGMCarl** [Adyen/adyen-magento2#735]
Please check:

https://github.com/Adyen/adyen-magento2/issues/664 (I could not reopen old issue....)

It is still not working. 

This is something really important and it's a disaster this is still not working correctly.

**Comment by acampos1916** [comment]
Hello @GGMCarl, thanks for opening this issue,

I see in the closed issue that you're reporting not being able to use Ratepay and get an "amount too high" exception, that doesn't seem to be related to the plugin like you noted. I gather that the cart total now matches and the issue was indeed solved? In that case #664 can remain closed.

Regarding the amount limit for Ratepay, [our support team can help you sort out the configuration in the Customer Area](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420). If you believe that this is not related to a configuration please open a new issue with the full exception message and scenario so we can look at it closely.

Best,
Ángel Campos
