### ISSUE TITLE
Klarna is unsupported when using a foreign currency

### ISSUE THREAD

**Issue by pascalexperius** [Adyen/adyen-magento2#746]
**Describe the bug**

**To Reproduce**
1. Go to Magento front-end and select the valuta "euro"
2. Add a product to the cart and click on "proceed to checkout"
3. Select the country "Denmark" or "England"

**Expected behavior**
A customer should be able to pay by Klarna. However, the payment option "Klarna" is only shown when the selected currency matches the country's default currency. So Klarna is only shown when using Danish krones in Denmark or GBP in England and is hidden when the euro is selected.

**Screenshots**

**Desktop (please complete the following information):**
- http://supportdetails.net/9874BI20

**Additional context**
- Magento 2.3.3p1
- Module version 6.1.1

**Comment by acampos1916** [comment]
Hello @pascalexperius,

Thank you for opening this issue. This is the expected behavior for Klarna payments, [check our documentation](https://docs.adyen.com/payment-methods/klarna/web-component#show-klarna-in-your-payment-form) for the combinations of country and currency that Klarna accepts.

Cheers,
Ángel
