### ISSUE TITLE
[PW-2639] Klarna error message in Magento check-out is incomplete

### ISSUE THREAD

**Issue by pascalexperius** [Adyen/adyen-magento2#747]
**Describe the bug**
When Klarna refuses an order because the phone number is incomplete, the Adyen module shows a (too) brief error "The requested Payment Method is not available". It would be better to show a more extensive message like "Your order is declided by Klarna, please select another method". Or even show the exact cause of the denial. 

**To Reproduce**
1. Go to Magento front-end and s
2. Add a product to the cart and click on "proceed to checkout"
3. Select an invalid phone number in the checkout

**Expected behavior**
Magento would show a clear error message, so the customer would know how he/she could complete the order.

**Screenshots**
![Klarna - Error](https://user-images.githubusercontent.com/58259042/85680689-d2880500-b6ca-11ea-83f0-43d9fa03dab6.png)

**Desktop (please complete the following information):**

**Describe the bug**
When Klarna refuses an order because the phone number is incomplete, the Adyen module shows a (too) brief error "The requested Payment Method is not available". It would be better to show a more extensive message like "Your order is declided by Klarna, please select another method". Or even show the exact cause of the denial. 

**To Reproduce**
1. Go to Magento front-end and s
2. Add a product to the cart and click on "proceed to checkout"
3. Select an invalid phone number in the checkout

**Expected behavior**
Magento would show a clear error message, so the customer would know how he/she could complete the order.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by acampos1916** [comment]
Hello @pascalexperius,

Thank you for opening this issue. I've created an internal ticket so we can look into it. We'll let you know of any progress made.

Cheers,
Ángel

**Comment by tnaber** [comment]
Hi @pascalexperius,

Sorry for this ticket not being picked up. I have investigated whether this problem is still relevant. I have tested the phone numbers in #749 and these are now accepted by Klarna. Additionally, in the current flow, it should not be possible to enter an incomplete phone number. 
Thinking about other potential errors I think the default error message 'Error with payment method please select different payment method.' suffices for now. I do agree that we should elaborate more on specifics wherever we can, however that applies not only to Klarna and is beyond the scope of this issue.

For these reasons I would like to close this ticket but I will leave it open for now as I might be missing some cases. Please let me know if that is the case and this is still an active problem for you :)

Cheers,
Titus
