### ISSUE TITLE
 [PW-2671] - Oney payment method always return error in test mode

### ISSUE THREAD

**Issue by zh-liang-eschimney** [Adyen/adyen-magento2#764]
**Describe the bug**
Oney payment method in French store always return error in test mode.

**To Reproduce**
1. Company account ESChimneySystemGmbh
2. Create a new web service user in test mode for Oney
3. We tried to test this method in our test server
4. When in check out, we set the country for France
5. And then appear the Oney payment method
6. It will first jump to redirecting, but the payment always fail
7. In Adyen backend you can see all the Oney payment failed, only credit card passed
8. And it has the reasons like: Acquirer Error (ERR_01 : Le champ est obligatoire)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**
One of the support reply "The field shopperreference  seems to be missing. Can you please make sure to include it ? Thanks ! " But we are using Magento 2, and we cannot add extra info in request, and we do not know where to put the shopperreference.
[adyen payment test  - Oney - 2.pdf](https://github.com/Adyen/adyen-magento2/files/4903483/adyen.payment.test.-.Oney.-.2.pdf)

**Comment by cyattilakiss** [comment]
Hi @zh-liang-eschimney

Thank you for raising this issue. I can reproduce it and indeed it looks like a bug. This payment method should not show up as a possible payment method for guest checkouts since the guest has no shopper reference available which is a requirement for this payment.

We are going to look into this issue and find a solution and/or propose a temporary solution asap.

A ticket has been created with the number: PW-2671

Best,
Attila
Adyen
