### ISSUE TITLE
Issues upgrading to Adyen module 6.0.0 or higher on our Magento 2.3.5-p1

### ISSUE THREAD

**Issue by benuta-Ben** [Adyen/adyen-magento2#769]
On our staging environment (running on 2.3.5-p1) we did update the Adyen module. We were still running on 5.4.0 and upgraded to v6.2.0. 

**Describe the bug**
In checkout after completely entering all neccessary info and clicking on "Place order", the screen is greyed out and the loading spinner animation is displayed endlessly.
 
the JS Error in browser console (Chrome) says: 
```
Uncaught TypeError: adyenPaymentService.getOrderPaymentStatus is not a function 
at Object .... at ... at... 
```

**To Reproduce**
1. Go to 'https://staging.benuta.eu/'
2. Create an account and set delivery address
3. Place sth in your Cart
4. Go to "Checkout"
5. Choose standard shipping, then click Next (there is only this one option)
6. Choose Credit card as payment method
7. Fill in test card data (https://docs.adyen.com/development-resources/test-cards/test-card-numbers)
8. Click "Place Order"

**Expected behavior**
Payment should be completed / triggered

**Screenshots**
![image](https://user-images.githubusercontent.com/7803396/87685193-678a9500-c783-11ea-8f0b-997988f8e208.png)

**Additional context**
The same happened when we wanted to upgrade to Adyen module 6.0.0. Since this was not a mandatory upgrade we did skip it. Now for security and other reasons we have to ensure to upgrade to latest version.

**Comment by acampos1916** [comment]
Hello @benuta-Ben, thank you for raising this issue.

I tried creating an account and using the checkout at https://staging.benuta.eu but there seems to be a problem with the session setup and couldn't verify the problem.

Nonetheless, I was able to test in a clean Magento2 installation with the 6.2.0 version of the plugin and the function is reachable and the problem is not reproducible. I see that the `getOrderPaymentStatus()` function is in the `adyen-payment-service.js` file and this is loaded during the checkout process using RequireJS. Is there a customization to the theme or assets that could be interfering with this? Could you check if the file is being loaded correctly using the browser console?

Ángel Campos

**Comment by benuta-Ben** [comment]
Thank you @acampos1916 ! ;) 
We'll check for the questions you asked. 

Meanwhile: 
It would be really helpful if you could try reproducing this on our system again, creating a user-account one more time, but this time with "incognito mode" activated in your browser, this will help you come across the session problem.

**Comment by AlexandrosMor** [comment]
Hello @benuta-Ben,

We cannot test with a test card in live environment. Looking forward for your answers.

kind regards,
Alexandros

**Comment by benuta-Ben** [comment]
Hi!
It seems, that we did find the reason for the error and were able to solve it. 
The error was caused by an Adyen IE11 patch. After removing the old patch the extension throws no errors and works like it should.
Thank you for your help, best 
benuta-Ben
