### ISSUE TITLE
Card payments still failing to redirect

### ISSUE THREAD

**Issue by JPaget17** [Adyen/adyen-magento2#815]
**Describe the bug**
When selecting the card option, after 3D security check, the redirect to success page fails. See Screenshot attached. This gives a payment review order in the admin of Magento 2. No money is transacted and the order isn't completed. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Place order with credit/debit card.
2. complete 3D Security with the card company (Visa/Mastercard/Amex) 
3. Error.

**Expected behavior**
Redirect to the Success page and completed order.

**Desktop (please complete the following information):**
 - OS: Windows 7 and 10
 - Browser: Chrome and Firefox
 - Version 85.0.4183.102 (Chome) - 80.0.1 (Chrome)

**Additional context**
Had the same issue with the Chrome same site cookies. This allowed card payments on other browsers. Now we have updated to the newest update we have this issue affecting all browsers. Currently have this option turned off in the Admin to avoid swamping customer service with queries. Klarna and Apple pay work fine. Was told by support to create this. 

It seems orders that don't have to go to 3D Security (1 previous customer) and test cards on our dev site, do not have this issue. Yet the vast majority of orders on our live site do. 

![image (8)](https://user-images.githubusercontent.com/70369131/93071457-152cfe00-f678-11ea-8e6b-af43dc7e8e2f.png)

**Comment by Anve94** [comment]
+1
Encountering the same problem for a live merchant. It seems to be related to some redirects after 3DS challenges which produce absurdly long URL's for the redirect token (over 6k charachters).

Sometimes 3ds challenges are returned through a Adyen URL, e.g. checkoutshopper-test.adyen.com/checkoutshopper/threeDS/return/<somestring>, other times the return URL goes to <merchant_domain_here>/adyen/process/redirect/<absurdly_long_token_here>. The latter causes an ERR_CONNECTION_CLOSED whereas the former works as expected. Which redirect flow is used seems to differ per bank/card issuer. I cannot simulate the second flow at all with the test cards provided here:https://docs.adyen.com/development-resources/test-cards/test-card-numbers#test-3d-secure-authentication which makes it a big pain to troubleshoot/debug.

**Comment by Anve94** [comment]
@JPaget17 

In my case the SSL offloader (powered by nginx) was unable to handle the URL length, so the server sent back an empty response. This is interpreted by chrome as an err_connection_closed. It also means the redirect never reaches the Magento installation at all. You can simulate the same error by just sending a very long URL to your magento instance.

We updated the http2_max_field_size config in the SSL offloader from the default 4k to 8k which makes longer URL's serviceable by the backend. We're keeping an eye on orders to see if this resolves the Adyen issue, but as of this writing this is yet unclear.

I do want to point out that updating the server configuration is not a proper fix, more a holdover, and am of firm believe that the redirect GET param values used by Adyen should be way shorter, so that it plays nice with a default nginx setup (not just for us but other Merchants as well whom will very likely face the same issues with these long URL's).

**Comment by JPaget17** [comment]
@Anve94 

Amazing! We just got our devs to do this, they added a couple more settings apparently and this looks to have worked for us. We are going to monitor orders and customer service queries throughout the day for orders that could be stuck in Payment Review. 

Thank you so much for sharing as this has been the best information we've received on this matter. Even after the new update! Really helpful

**Comment by lewisvoncken** [comment]
http2_max_field_size 16k;

worked for me!

But in my opinion this shouldn't be necessary and the parameter should be shorter.

**Comment by fahu** [comment]
Duplicate of #853

**Comment by floorjubbega** [comment]
Issue resolved in #859, we suggest to update to the latest released version of our plugin to resolve this issue
