### ISSUE TITLE
6.6.1, dans le fichier /etc/module.xml, la version reste en setup_version="5.4.0

### ISSUE THREAD

**Issue by zobba** [Adyen/adyen-magento2#855]
**Describe the bug**

**To Reproduce**

**Expected behavior**
cela va poser le problème quand on mettre à jour le module par composer.

nous avons quand même réussi à installer la nouvelle version, c'est pas grande chose à corriger, mais qui facilite les gens.

**Screenshots**
![sc](https://user-images.githubusercontent.com/7924805/96688197-2b1d9500-1381-11eb-9865-dd88d3c46875.jpg)

**Comment by cyattilakiss** [comment]
Hi @zobba ,

Thank you for raising this issue.
When there is no migration script for the upgrade we only bump the composer.json module version number so during the upgrade of the plugins Magento knows that it's not needed to run any migration script for the plugin.
Was there any issue you faced during the update because this version was not updated?

@floorjubbega has already created a PR for this but we will keep this on hold until your response.

Thank you in advance,
Attila
Adyen

**Comment by zobba** [comment]
Hi Attila,

No, we did not have any issue, but it creates confusion, because we systematically look at this file to avoid error.

Thank you :)

**Comment by cyattilakiss** [comment]
Hi @zobba ,

Thank you for the response and sorry for the confusion :) 
We follow the Magento guideline here: "Module version indicates the current version of the database schema and data, and is used in upgrading" and update it when we update the database schema and data.
I will close this issue and the PR from @floorjubbega regarding this issue.

Best,
Attila
Adyen
