### ISSUE TITLE
Google Pay, leaving orders on Payment Review status and payment is left as an offer.

### ISSUE THREAD

**Issue by TGCTech** [Adyen/adyen-magento2#860]
**Describe the bug**
Magento 2 Extension 6.6.1 / Magento version 2.3.4

When a customer selects Google Pay at the checkout, the system appears to process the payment on the frontend, and the customer is presented with the order success page with an order number and the 'thank you for your order' message, but the order status is left on 'Payment Review' in the backend and when we log into the Adyen portal, the payment only appears as an 'offer' and not as a successful payment.

Therefore we have a customer who believes they have placed their order successfully, but the payment has in fact not been processed.

Any ideas?

**Comment by AlexandrosMor** [comment]
Hello @TGCTech,

We are currently working in google pay and  there is a PR #870 with the fix for 3DS1. 
Testing the google pay in the previous version it is still Authorised and not an offer in Adyen's backoffice. 
When the pr is reviewed and merged you can test again with develop

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @TGCTech,

This issue was solved in the latest magento [release 6.6.5](https://github.com/Adyen/adyen-magento2/releases/tag/6.6.5)

regards,
Alexandros
