### ISSUE TITLE
[PW-3462] Bancontact is stored as Maestro in Magento

### ISSUE THREAD

**Issue by Jurhillebrink** [Adyen/adyen-magento2#875]
**Describe the bug**
Orders with the Bancontact payment method (bcmc) will correctly saved in Adyen as Bancontact but as Maestro (MI) in Magento. 

**To Reproduce**
1. Created an order with payment method 'bancontact'
2. Go to the order in the Magento admin and check the payment method.
3. Also you can see it in the sales_order_payment table under cc_type.

**Expected behavior**
The Bancontact payment is stored as bcmc in Magento

**Comment by cyattilakiss** [comment]
Hi @Jurhillebrink ,

Thank you for raising this issue.

I've just double checked it on my dev environment with the test cards: `6703 4444 4444 4449` and `6703 0000 0000 0000 003` and indeed this is the case. In the past with the cobranded cards we had quite a lot of issues and that's the reason we always treated them a bit differently. I actually found the piece of code where we manually change BCMC to Maestro here: https://github.com/Adyen/adyen-magento2/blob/6.6.5/view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js#L194-L199

I will create an internal ticket to investigate if removing those lines would be working now with the new components and APIs.

Best,
Attila
Adyen

**Comment by ebaschiera** [comment]
Hi @cyattilakiss ,
I am not sure if this is related, but we noticed that payments with BCMC in our merchant accounts were not treated as SALE payments, but as AUTH.
This led to have invoiced orders in Magento and authorized transactions on Adyen (not captured). That's not correct, because Magento cannot capture payments when orders are already invoiced. So if you configure the merchant account to use manual capture, those BCMC transactions are outside the Magento domain and have to be captured manually from Adyen Customer Area.
Thanks!

**Comment by AlexandrosMor** [comment]
Hello @ebaschiera, @Jurhillebrink,

We removed this mapping and open a [pr](https://github.com/Adyen/adyen-magento2/pull/899) for this fix. If you are facing the same issue after this PR then please reach out to support. The bcmc has fallback maestro and in the payment methods settings for your merchant account it should be set as higher priority. 

kind regards,
Alexandros
