### ISSUE TITLE
Load error adyen.min.js (if has minify js enabled)

### ISSUE THREAD

**Issue by way2ecommerce** [Adyen/adyen-magento2#912]
**Description**
If Magento has minify enabled add "adyen.**min**.js" to this js external file "https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/3.4.0/adyen.js"

**To Reproduce**
1. Go to 'checkout' with minify enabled on production mode
4. See error on firebug or developer console

**Comment by walkwizus** [comment]
There are an update for this issue ?

**Comment by AlexandrosMor** [comment]
Hello @way2ecommerce,

Thank you for raising this issue. Could you send us the adyen-magento2 plugin version that you are using ? This issue is fixed in the plugin version [6.6.0](https://github.com/Adyen/adyen-magento2/releases/tag/6.6.0)  

regards,
Alexandros

**Comment by walkwizus** [comment]
I use the 6.6.8 and it's not fix.

**Comment by walkwizus** [comment]
In production mode Magento call this URL: https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/3.4.0/adyen.min.js As you can see there are a 404.

**Comment by AlexandrosMor** [comment]
hello @walkwizus,

In order to exclude the adyen.js for minificaition we need to change the etc/config.xml but it is not compatible with magento 2.2. We introduce a fix compatible with 2.2 and 2.3 in the version 7 which is not released yet. You can fix it by following this [pull request](https://github.com/Adyen/adyen-magento2/pull/816/files) until the adyen plugin version 7 is released

Kind regards,
Alexandros
